name: agua_clara
version: '1.0.0'
config-version: 2

profile: agua_clara

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:

  agua_clara:

    l4_fact:
      +schema: l4_fact
      +materialized: table

    silver_edw:
      +schema: silver_edw
      +materialized: table

    silver_fact:
      +schema: silver_fact
      +materialized: table

    gold_fact:
      +schema: gold_fact
      +materialized: table

flags:
  require_generic_test_arguments_property: true

seeds:
  agua_clara:
    gold_fact:
      +schema: gold_fact
      +quote_columns: false
      g_s_concepto_clasificacion:
        +column_types:
          CODIGO_CONCEPTO: varchar(50)
          CODIGO_ORIGEN: varchar(30)
          ORIGEN_CONCEPTO: varchar(50)
          GRUPO_FUNCIONAL: varchar(50)
          ES_CONSUMO: boolean
          ES_SERVICIO: boolean
          ES_TRIBUTO: boolean
          ES_BONIFICACION: boolean
          ES_IVA: boolean
          ES_ADITIVO: boolean  