{{ config(
    severity='error',
    store_failures=true,
    tags=['reconciliation', 'reconciliation_l4_silver_edw']
) }}

/*
   Reconciliación L4 -> SILVER_EDW para Hubs.

   Devuelve únicamente incidencias:
   - COUNT_MISMATCH: diferencia de volumetría.
   - MISSING_IN_SILVER: clave esperada en L4 que no existe en el Hub.
   - UNEXPECTED_IN_SILVER: clave presente en el Hub que ya no aparece en la imagen actual L4.

   UNEXPECTED_IN_SILVER se clasifica como WARN porque los Hubs son append-only y
   pueden conservar claves históricas que ya no estén presentes en la imagen actual de L4.
*/

WITH expected_keys AS (

    SELECT 'MUNICIPI_SGAB' AS OBJECT_NAME, 'edw_h_municipi_sgab' AS SILVER_MODEL, 'l4_municipi_sgab' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(TO_VARCHAR(NUM_MUN_SGAB))), 256) AS HASH_KEY, TO_VARCHAR(NUM_MUN_SGAB) AS BUSINESS_KEY FROM {{ ref('l4_municipi_sgab') }} WHERE NUM_MUN_SGAB IS NOT NULL

    UNION ALL

SELECT 'CONVENI_FRAU' AS OBJECT_NAME, 'edw_h_conveni_frau' AS SILVER_MODEL, 'l4_conveni_frau' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(TO_VARCHAR(POLISSA_SUBM))), 256) AS HASH_KEY, TO_VARCHAR(POLISSA_SUBM) AS BUSINESS_KEY FROM {{ ref('l4_conveni_frau') }} WHERE NULLIF(TRIM(POLISSA_SUBM), '') IS NOT NULL

    UNION ALL

SELECT 'HIST_SS_PE' AS OBJECT_NAME, 'edw_h_hist_ss_pe' AS SILVER_MODEL, 'l4_hist_ss_pe' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(POLISSA_SUBM)), UPPER(TRIM(TIP_COLECTIVO)), TO_VARCHAR(TS_MOM_IND, 'YYYY-MM-DD HH24:MI:SS.FF9')), 256) AS HASH_KEY, CONCAT_WS('|', POLISSA_SUBM, TIP_COLECTIVO, TO_VARCHAR(TS_MOM_IND, 'YYYY-MM-DD HH24:MI:SS.FF9')) AS BUSINESS_KEY FROM {{ ref('l4_hist_ss_pe') }} WHERE NULLIF(TRIM(POLISSA_SUBM), '') IS NOT NULL AND NULLIF(TRIM(TIP_COLECTIVO), '') IS NOT NULL AND TS_MOM_IND IS NOT NULL

    UNION ALL

SELECT 'PADRO_TRR' AS OBJECT_NAME, 'edw_h_padro_trr' AS SILVER_MODEL, 'l4_padro_trr' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(POLISSA_SUBM)), TO_VARCHAR(TS_PADRO_TRR, 'YYYY-MM-DD HH24:MI:SS.FF9')), 256) AS HASH_KEY, CONCAT_WS('|', POLISSA_SUBM, TO_VARCHAR(TS_PADRO_TRR, 'YYYY-MM-DD HH24:MI:SS.FF9')) AS BUSINESS_KEY FROM {{ ref('l4_padro_trr') }} WHERE NULLIF(TRIM(POLISSA_SUBM), '') IS NOT NULL AND TS_PADRO_TRR IS NOT NULL

    UNION ALL

SELECT 'PADRO_TAMGREM' AS OBJECT_NAME, 'edw_h_padro_tamgrem' AS SILVER_MODEL, 'l4_padro_tamgrem' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(POLISSA_SUBM)), TO_VARCHAR(TS_PADRO_TAMGREM, 'YYYY-MM-DD HH24:MI:SS.FF9')), 256) AS HASH_KEY, CONCAT_WS('|', POLISSA_SUBM, TO_VARCHAR(TS_PADRO_TAMGREM, 'YYYY-MM-DD HH24:MI:SS.FF9')) AS BUSINESS_KEY FROM {{ ref('l4_padro_tamgrem') }} WHERE NULLIF(TRIM(POLISSA_SUBM), '') IS NOT NULL AND TS_PADRO_TAMGREM IS NOT NULL

    UNION ALL

SELECT 'DTE_MUNICIPAL' AS OBJECT_NAME, 'edw_h_dte_municipal' AS SILVER_MODEL, 'l4_dte_municipal' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(TO_VARCHAR(NUM_MUN_SGAB))), UPPER(TRIM(TO_VARCHAR(NUM_DTE_MUNI)))), 256) AS HASH_KEY, CONCAT_WS('|', NUM_MUN_SGAB, NUM_DTE_MUNI) AS BUSINESS_KEY FROM {{ ref('l4_dte_municipal') }} WHERE NUM_MUN_SGAB IS NOT NULL AND NUM_DTE_MUNI IS NOT NULL

    UNION ALL

SELECT 'TARIFA_FACTURACIO' AS OBJECT_NAME, 'edw_h_tarifa_facturacio' AS SILVER_MODEL, 'l4_tarifa_facturacio' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(TIP_TARIFA)), UPPER(TRIM(SUBTIP_TARIFA)), TO_VARCHAR(DATA_INI_VIGENCIA, 'YYYY-MM-DD')), 256) AS HASH_KEY, CONCAT_WS('|', TIP_TARIFA, SUBTIP_TARIFA, TO_VARCHAR(DATA_INI_VIGENCIA, 'YYYY-MM-DD')) AS BUSINESS_KEY FROM {{ ref('l4_tarifa_facturacio') }} WHERE NULLIF(TRIM(TIP_TARIFA), '') IS NOT NULL AND NULLIF(TRIM(SUBTIP_TARIFA), '') IS NOT NULL AND DATA_INI_VIGENCIA IS NOT NULL

    UNION ALL

SELECT 'EPIGRAF_IAE' AS OBJECT_NAME, 'edw_h_epigraf_iae' AS SILVER_MODEL, 'l4_epigraf_iae' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(SECCIO)), UPPER(TRIM(EPIGRAF_IAE))), 256) AS HASH_KEY, CONCAT_WS('|', SECCIO, EPIGRAF_IAE) AS BUSINESS_KEY FROM {{ ref('l4_epigraf_iae') }} WHERE NULLIF(TRIM(SECCIO), '') IS NOT NULL AND NULLIF(TRIM(EPIGRAF_IAE), '') IS NOT NULL

    UNION ALL

SELECT 'CARRER' AS OBJECT_NAME, 'edw_h_carrer' AS SILVER_MODEL, 'l4_carrer' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(TO_VARCHAR(NUM_MUN_SGAB))), TO_VARCHAR(NUM_CARRER)), 256) AS HASH_KEY, CONCAT_WS('|', NUM_MUN_SGAB, TO_VARCHAR(NUM_CARRER)) AS BUSINESS_KEY FROM {{ ref('l4_carrer') }} WHERE NUM_MUN_SGAB IS NOT NULL AND NUM_CARRER IS NOT NULL

    UNION ALL

SELECT 'FINCA' AS OBJECT_NAME, 'edw_h_finca' AS SILVER_MODEL, 'l4_finca' AS L4_MODEL, SHA2_HEX(CONCAT_WS('|', UPPER(TRIM(TO_VARCHAR(NUM_MUN_SGAB))), TO_VARCHAR(NUM_CARRER), UPPER(TRIM(TO_VARCHAR(NUM_INI_FINCA))), COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_INI_FINCA)),''),'^^'), UPPER(TRIM(TO_VARCHAR(NUM_FIN_FINCA))), COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_FIN_FINCA)),''),'^^'), UPPER(TRIM(TO_VARCHAR(SIT_FINCA_ESPEC))), TO_VARCHAR(ORD_FINCA_ESPEC)), 256) AS HASH_KEY, CONCAT_WS('|', NUM_MUN_SGAB, NUM_CARRER, NUM_INI_FINCA, COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_INI_FINCA)),''),'^^'), NUM_FIN_FINCA, COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_FIN_FINCA)),''),'^^'), SIT_FINCA_ESPEC, ORD_FINCA_ESPEC) AS BUSINESS_KEY FROM {{ ref('l4_finca') }} WHERE NUM_MUN_SGAB IS NOT NULL AND NUM_CARRER IS NOT NULL AND NUM_INI_FINCA IS NOT NULL AND NUM_FIN_FINCA IS NOT NULL AND SIT_FINCA_ESPEC IS NOT NULL AND ORD_FINCA_ESPEC IS NOT NULL

    UNION ALL

SELECT 'RAMAL' AS OBJECT_NAME, 'edw_h_ramal' AS SILVER_MODEL, 'l4_ramal' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(POLISSA_RAMAL)), 256) AS HASH_KEY, POLISSA_RAMAL AS BUSINESS_KEY FROM {{ ref('l4_ramal') }} WHERE NULLIF(TRIM(POLISSA_RAMAL), '') IS NOT NULL

    UNION ALL

SELECT 'SUBMIN_SERVEI' AS OBJECT_NAME, 'edw_h_submin_servei' AS SILVER_MODEL, 'l4_submin_servei' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(POLISSA_SUBM)), 256) AS HASH_KEY, POLISSA_SUBM AS BUSINESS_KEY FROM {{ ref('l4_submin_servei') }} WHERE NULLIF(TRIM(POLISSA_SUBM), '') IS NOT NULL

    UNION ALL

SELECT 'SERVEI_EQ_CI' AS OBJECT_NAME, 'edw_h_servei_eq_ci' AS SILVER_MODEL, 'l4_servei_eq_ci' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(POLISSA_SUBM)), 256) AS HASH_KEY, POLISSA_SUBM AS BUSINESS_KEY FROM {{ ref('l4_servei_eq_ci') }} WHERE NULLIF(TRIM(POLISSA_SUBM), '') IS NOT NULL

    UNION ALL

SELECT 'TIPO_VIVIENDA' AS OBJECT_NAME, 'edw_h_tipo_vivienda' AS SILVER_MODEL, 'l4_codificacions' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(CLAU_CODI)), 256) AS HASH_KEY, CLAU_CODI AS BUSINESS_KEY FROM {{ ref('l4_codificacions') }} WHERE TIP_CODI = 'THL' AND NULLIF(TRIM(CLAU_CODI), '') IS NOT NULL

    UNION ALL

SELECT 'TIPO_SUMINISTRO' AS OBJECT_NAME, 'edw_h_tipo_suministro' AS SILVER_MODEL, 'l4_codificacions' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(CLAU_CODI)), 256) AS HASH_KEY, CLAU_CODI AS BUSINESS_KEY FROM {{ ref('l4_codificacions') }} WHERE TIP_CODI = 'TSS' AND NULLIF(TRIM(CLAU_CODI), '') IS NOT NULL

    UNION ALL

SELECT 'TIPO_USO_AGUA' AS OBJECT_NAME, 'edw_h_tipo_uso_agua' AS SILVER_MODEL, 'l4_codificacions' AS L4_MODEL, SHA2_HEX(UPPER(TRIM(CLAU_CODI)), 256) AS HASH_KEY, CLAU_CODI AS BUSINESS_KEY FROM {{ ref('l4_codificacions') }} WHERE TIP_CODI = 'US' AND NULLIF(TRIM(CLAU_CODI), '') IS NOT NULL

),

actual_keys AS (

    SELECT 'MUNICIPI_SGAB' AS OBJECT_NAME, 'edw_h_municipi_sgab' AS SILVER_MODEL, 'l4_municipi_sgab' AS L4_MODEL, HK_MUNICIPI_SGAB AS HASH_KEY FROM {{ ref('edw_h_municipi_sgab') }}

    UNION ALL

SELECT 'CONVENI_FRAU' AS OBJECT_NAME, 'edw_h_conveni_frau' AS SILVER_MODEL, 'l4_conveni_frau' AS L4_MODEL, HK_CONVENI_FRAU AS HASH_KEY FROM {{ ref('edw_h_conveni_frau') }}

    UNION ALL

SELECT 'HIST_SS_PE' AS OBJECT_NAME, 'edw_h_hist_ss_pe' AS SILVER_MODEL, 'l4_hist_ss_pe' AS L4_MODEL, HK_HIST_SS_PE AS HASH_KEY FROM {{ ref('edw_h_hist_ss_pe') }}

    UNION ALL

SELECT 'PADRO_TRR' AS OBJECT_NAME, 'edw_h_padro_trr' AS SILVER_MODEL, 'l4_padro_trr' AS L4_MODEL, HK_PADRO_TRR AS HASH_KEY FROM {{ ref('edw_h_padro_trr') }}

    UNION ALL

SELECT 'PADRO_TAMGREM' AS OBJECT_NAME, 'edw_h_padro_tamgrem' AS SILVER_MODEL, 'l4_padro_tamgrem' AS L4_MODEL, HK_PADRO_TAMGREM AS HASH_KEY FROM {{ ref('edw_h_padro_tamgrem') }}

    UNION ALL

SELECT 'DTE_MUNICIPAL' AS OBJECT_NAME, 'edw_h_dte_municipal' AS SILVER_MODEL, 'l4_dte_municipal' AS L4_MODEL, HK_DTE_MUNICIPAL AS HASH_KEY FROM {{ ref('edw_h_dte_municipal') }}

    UNION ALL

SELECT 'TARIFA_FACTURACIO' AS OBJECT_NAME, 'edw_h_tarifa_facturacio' AS SILVER_MODEL, 'l4_tarifa_facturacio' AS L4_MODEL, HK_TARIFA_FACTURACIO AS HASH_KEY FROM {{ ref('edw_h_tarifa_facturacio') }}

    UNION ALL

SELECT 'EPIGRAF_IAE' AS OBJECT_NAME, 'edw_h_epigraf_iae' AS SILVER_MODEL, 'l4_epigraf_iae' AS L4_MODEL, HK_EPIGRAF_IAE AS HASH_KEY FROM {{ ref('edw_h_epigraf_iae') }}

    UNION ALL

SELECT 'CARRER' AS OBJECT_NAME, 'edw_h_carrer' AS SILVER_MODEL, 'l4_carrer' AS L4_MODEL, HK_CARRER AS HASH_KEY FROM {{ ref('edw_h_carrer') }}

    UNION ALL

SELECT 'FINCA' AS OBJECT_NAME, 'edw_h_finca' AS SILVER_MODEL, 'l4_finca' AS L4_MODEL, HK_FINCA AS HASH_KEY FROM {{ ref('edw_h_finca') }}

    UNION ALL

SELECT 'RAMAL' AS OBJECT_NAME, 'edw_h_ramal' AS SILVER_MODEL, 'l4_ramal' AS L4_MODEL, HK_RAMAL AS HASH_KEY FROM {{ ref('edw_h_ramal') }}

    UNION ALL

SELECT 'SUBMIN_SERVEI' AS OBJECT_NAME, 'edw_h_submin_servei' AS SILVER_MODEL, 'l4_submin_servei' AS L4_MODEL, HK_SUBMIN_SERVEI AS HASH_KEY FROM {{ ref('edw_h_submin_servei') }}

    UNION ALL

SELECT 'SERVEI_EQ_CI' AS OBJECT_NAME, 'edw_h_servei_eq_ci' AS SILVER_MODEL, 'l4_servei_eq_ci' AS L4_MODEL, HK_SERVEI_EQ_CI AS HASH_KEY FROM {{ ref('edw_h_servei_eq_ci') }}

    UNION ALL

SELECT 'TIPO_VIVIENDA' AS OBJECT_NAME, 'edw_h_tipo_vivienda' AS SILVER_MODEL, 'l4_codificacions' AS L4_MODEL, HK_TIPO_VIVIENDA AS HASH_KEY FROM {{ ref('edw_h_tipo_vivienda') }}

    UNION ALL

SELECT 'TIPO_SUMINISTRO' AS OBJECT_NAME, 'edw_h_tipo_suministro' AS SILVER_MODEL, 'l4_codificacions' AS L4_MODEL, HK_TIPO_SUMINISTRO AS HASH_KEY FROM {{ ref('edw_h_tipo_suministro') }}

    UNION ALL

SELECT 'TIPO_USO_AGUA' AS OBJECT_NAME, 'edw_h_tipo_uso_agua' AS SILVER_MODEL, 'l4_codificacions' AS L4_MODEL, HK_TIPO_USO_AGUA AS HASH_KEY FROM {{ ref('edw_h_tipo_uso_agua') }}

),

expected_distinct AS (

    SELECT DISTINCT
        OBJECT_NAME,
        SILVER_MODEL,
        L4_MODEL,
        HASH_KEY,
        BUSINESS_KEY
    FROM expected_keys

),

actual_distinct AS (

    SELECT DISTINCT
        OBJECT_NAME,
        SILVER_MODEL,
        L4_MODEL,
        HASH_KEY
    FROM actual_keys

),

counts AS (

    SELECT
        COALESCE(e.OBJECT_NAME, a.OBJECT_NAME) AS OBJECT_NAME,
        COALESCE(e.SILVER_MODEL, a.SILVER_MODEL) AS SILVER_MODEL,
        COALESCE(e.L4_MODEL, a.L4_MODEL) AS L4_MODEL,
        COALESCE(e.L4_COUNT, 0) AS L4_COUNT,
        COALESCE(a.SILVER_COUNT, 0) AS SILVER_COUNT
    FROM (
        SELECT OBJECT_NAME, SILVER_MODEL, L4_MODEL, COUNT(*) AS L4_COUNT
        FROM expected_distinct
        GROUP BY OBJECT_NAME, SILVER_MODEL, L4_MODEL
    ) AS e
    FULL OUTER JOIN (
        SELECT OBJECT_NAME, SILVER_MODEL, L4_MODEL, COUNT(*) AS SILVER_COUNT
        FROM actual_distinct
        GROUP BY OBJECT_NAME, SILVER_MODEL, L4_MODEL
    ) AS a
        ON a.OBJECT_NAME = e.OBJECT_NAME

),

count_issues AS (

    SELECT
        'COUNT_MISMATCH' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        OBJECT_NAME,
        SILVER_MODEL,
        L4_MODEL,
        CAST(NULL AS VARCHAR) AS HASH_KEY,
        CAST(NULL AS VARCHAR) AS BUSINESS_KEY,
        L4_COUNT,
        SILVER_COUNT,
        SILVER_COUNT - L4_COUNT AS COUNT_DIFFERENCE,
        'KO' AS RECONCILIATION_STATUS
    FROM counts
    WHERE SILVER_COUNT <> L4_COUNT

),

missing_in_silver AS (

    SELECT
        'MISSING_IN_SILVER' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        e.OBJECT_NAME,
        e.SILVER_MODEL,
        e.L4_MODEL,
        e.HASH_KEY,
        e.BUSINESS_KEY,
        CAST(NULL AS NUMBER) AS L4_COUNT,
        CAST(NULL AS NUMBER) AS SILVER_COUNT,
        CAST(NULL AS NUMBER) AS COUNT_DIFFERENCE,
        'KO' AS RECONCILIATION_STATUS
    FROM expected_distinct AS e
    LEFT JOIN actual_distinct AS a
        ON a.OBJECT_NAME = e.OBJECT_NAME
       AND a.HASH_KEY = e.HASH_KEY
    WHERE a.HASH_KEY IS NULL

),

unexpected_in_silver AS (

    SELECT
        'UNEXPECTED_IN_SILVER' AS CONTROL_TYPE,
        'WARN' AS SEVERITY,
        a.OBJECT_NAME,
        a.SILVER_MODEL,
        a.L4_MODEL,
        a.HASH_KEY,
        CAST(NULL AS VARCHAR) AS BUSINESS_KEY,
        CAST(NULL AS NUMBER) AS L4_COUNT,
        CAST(NULL AS NUMBER) AS SILVER_COUNT,
        CAST(NULL AS NUMBER) AS COUNT_DIFFERENCE,
        'WARN' AS RECONCILIATION_STATUS
    FROM actual_distinct AS a
    LEFT JOIN expected_distinct AS e
        ON e.OBJECT_NAME = a.OBJECT_NAME
       AND e.HASH_KEY = a.HASH_KEY
    WHERE e.HASH_KEY IS NULL

)

SELECT * FROM count_issues
UNION ALL
SELECT * FROM missing_in_silver
UNION ALL
SELECT * FROM unexpected_in_silver
