{{ config(
    severity='error',
    store_failures=true,
    tags=['reconciliation', 'reconciliation_raw_l4']
) }}

/*
    Reconciliacion RAW -> L4 para las 22 tablas del piloto.

    La consulta devuelve exclusivamente incidencias. Como test singular,
    una ejecucion correcta devuelve cero filas.

    Controles:
      - COUNT_MISMATCH: diferencia de numero total de filas.
      - INVALID_RAW_KEY: filas RAW cuya clave natural es nula o no convertible.
      - DUPLICATE_RAW_KEY: claves naturales repetidas en RAW.
      - DUPLICATE_L4_KEY: claves naturales repetidas en L4.
      - MISSING_IN_L4: claves RAW validas que no llegaron a L4.
      - UNEXPECTED_IN_L4: claves L4 sin correspondencia en la imagen RAW.

    Nota: FACT_REGUL y FACT_RECUP se incluyen aunque actualmente esten vacias.
    Si RAW y L4 contienen cero filas, no generan ninguna incidencia.
*/

WITH row_counts AS (

    SELECT 'CODIFICACIONS' AS OBJECT_NAME, 'raw_codificacions' AS RAW_MODEL, 'l4_codificacions' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_codificacions') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_codificacions') }}) AS L4_COUNT

    UNION ALL

SELECT 'MUNICIPI_SGAB' AS OBJECT_NAME, 'raw_municipi_sgab' AS RAW_MODEL, 'l4_municipi_sgab' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_municipi_sgab') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_municipi_sgab') }}) AS L4_COUNT

    UNION ALL

SELECT 'DTE_MUNICIPAL' AS OBJECT_NAME, 'raw_dte_municipal' AS RAW_MODEL, 'l4_dte_municipal' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_dte_municipal') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_dte_municipal') }}) AS L4_COUNT

    UNION ALL

SELECT 'EPIGRAF_IAE' AS OBJECT_NAME, 'raw_epigraf_iae' AS RAW_MODEL, 'l4_epigraf_iae' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_epigraf_iae') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_epigraf_iae') }}) AS L4_COUNT

    UNION ALL

SELECT 'CARRER' AS OBJECT_NAME, 'raw_carrer' AS RAW_MODEL, 'l4_carrer' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_carrer') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_carrer') }}) AS L4_COUNT

    UNION ALL

SELECT 'FINCA' AS OBJECT_NAME, 'raw_finca' AS RAW_MODEL, 'l4_finca' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_finca') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_finca') }}) AS L4_COUNT

    UNION ALL

SELECT 'RAMAL' AS OBJECT_NAME, 'raw_ramal' AS RAW_MODEL, 'l4_ramal' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_ramal') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_ramal') }}) AS L4_COUNT

    UNION ALL

SELECT 'SUBMIN_SERVEI' AS OBJECT_NAME, 'raw_submin_servei' AS RAW_MODEL, 'l4_submin_servei' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_submin_servei') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_submin_servei') }}) AS L4_COUNT

    UNION ALL

SELECT 'SUBMIN_IAE' AS OBJECT_NAME, 'raw_submin_iae' AS RAW_MODEL, 'l4_submin_iae' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_submin_iae') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_submin_iae') }}) AS L4_COUNT

    UNION ALL

SELECT 'PADRO_TRR' AS OBJECT_NAME, 'raw_padro_trr' AS RAW_MODEL, 'l4_padro_trr' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_padro_trr') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_padro_trr') }}) AS L4_COUNT

    UNION ALL

SELECT 'PADRO_TAMGREM' AS OBJECT_NAME, 'raw_padro_tamgrem' AS RAW_MODEL, 'l4_padro_tamgrem' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_padro_tamgrem') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_padro_tamgrem') }}) AS L4_COUNT

    UNION ALL

SELECT 'HIST_SS_PE' AS OBJECT_NAME, 'raw_hist_ss_pe' AS RAW_MODEL, 'l4_hist_ss_pe' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_hist_ss_pe') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_hist_ss_pe') }}) AS L4_COUNT

    UNION ALL

SELECT 'SERVEI_EQ_CI' AS OBJECT_NAME, 'raw_servei_eq_ci' AS RAW_MODEL, 'l4_servei_eq_ci' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_servei_eq_ci') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_servei_eq_ci') }}) AS L4_COUNT

    UNION ALL

SELECT 'SERVEI_FACTURAR' AS OBJECT_NAME, 'raw_servei_facturar' AS RAW_MODEL, 'l4_servei_facturar' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_servei_facturar') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_servei_facturar') }}) AS L4_COUNT

    UNION ALL

SELECT 'CONVENI_FRAU' AS OBJECT_NAME, 'raw_conveni_frau' AS RAW_MODEL, 'l4_conveni_frau' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_conveni_frau') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_conveni_frau') }}) AS L4_COUNT

    UNION ALL

SELECT 'FACT_RESUM' AS OBJECT_NAME, 'raw_fact_resum' AS RAW_MODEL, 'l4_fact_resum' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_fact_resum') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_fact_resum') }}) AS L4_COUNT

    UNION ALL

SELECT 'FACT_AIGUA' AS OBJECT_NAME, 'raw_fact_aigua' AS RAW_MODEL, 'l4_fact_aigua' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_fact_aigua') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_fact_aigua') }}) AS L4_COUNT

    UNION ALL

SELECT 'FACT_CONCEPTE' AS OBJECT_NAME, 'raw_fact_concepte' AS RAW_MODEL, 'l4_fact_concepte' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_fact_concepte') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_fact_concepte') }}) AS L4_COUNT

    UNION ALL

SELECT 'FACT_REGUL' AS OBJECT_NAME, 'raw_fact_regul' AS RAW_MODEL, 'l4_fact_regul' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_fact_regul') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_fact_regul') }}) AS L4_COUNT

    UNION ALL

SELECT 'FACT_RECUP' AS OBJECT_NAME, 'raw_fact_recup' AS RAW_MODEL, 'l4_fact_recup' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_fact_recup') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_fact_recup') }}) AS L4_COUNT

    UNION ALL

SELECT 'SITUACIO_FACT' AS OBJECT_NAME, 'raw_situacio_fact' AS RAW_MODEL, 'l4_situacio_fact' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_situacio_fact') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_situacio_fact') }}) AS L4_COUNT

    UNION ALL

SELECT 'TARIFA_FACTURACIO' AS OBJECT_NAME, 'raw_tarifa_facturacio' AS RAW_MODEL, 'l4_tarifa_facturacio' AS L4_MODEL, (SELECT COUNT(*) FROM {{ source('raw_sicab', 'raw_tarifa_facturacio') }}) AS RAW_COUNT, (SELECT COUNT(*) FROM {{ ref('l4_tarifa_facturacio') }}) AS L4_COUNT

),

raw_key_rows AS (

    SELECT 'CODIFICACIONS' AS OBJECT_NAME, 'raw_codificacions' AS RAW_MODEL, 'l4_codificacions' AS L4_MODEL, IFF(NULLIF(TRIM(TIP_CODI),'') IS NOT NULL AND NULLIF(TRIM(CLAU_CODI),'') IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(TIP_CODI)),UPPER(TRIM(CLAU_CODI))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(TIP_CODI),'') IS NOT NULL AND NULLIF(TRIM(CLAU_CODI),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_codificacions') }}

    UNION ALL

SELECT 'MUNICIPI_SGAB' AS OBJECT_NAME, 'raw_municipi_sgab' AS RAW_MODEL, 'l4_municipi_sgab' AS L4_MODEL, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL, UPPER(TRIM(NUM_MUN_SGAB)), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_municipi_sgab') }}

    UNION ALL

SELECT 'DTE_MUNICIPAL' AS OBJECT_NAME, 'raw_dte_municipal' AS RAW_MODEL, 'l4_dte_municipal' AS L4_MODEL, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL AND NULLIF(TRIM(NUM_DTE_MUNI),'') IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(NUM_MUN_SGAB)),UPPER(TRIM(NUM_DTE_MUNI))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL AND NULLIF(TRIM(NUM_DTE_MUNI),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_dte_municipal') }}

    UNION ALL

SELECT 'EPIGRAF_IAE' AS OBJECT_NAME, 'raw_epigraf_iae' AS RAW_MODEL, 'l4_epigraf_iae' AS L4_MODEL, IFF(NULLIF(TRIM(SECCIO),'') IS NOT NULL AND NULLIF(TRIM(EPIGRAF_IAE),'') IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(SECCIO)),UPPER(TRIM(EPIGRAF_IAE))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(SECCIO),'') IS NOT NULL AND NULLIF(TRIM(EPIGRAF_IAE),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_epigraf_iae') }}

    UNION ALL

SELECT 'CARRER' AS OBJECT_NAME, 'raw_carrer' AS RAW_MODEL, 'l4_carrer' AS L4_MODEL, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_CARRER) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(NUM_MUN_SGAB)),TO_VARCHAR(TRY_TO_NUMBER(NUM_CARRER))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_CARRER) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_carrer') }}

    UNION ALL

SELECT 'FINCA' AS OBJECT_NAME, 'raw_finca' AS RAW_MODEL, 'l4_finca' AS L4_MODEL, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_CARRER) IS NOT NULL AND NULLIF(TRIM(NUM_INI_FINCA),'') IS NOT NULL AND NULLIF(TRIM(NUM_FIN_FINCA),'') IS NOT NULL AND SIT_FINCA_ESPEC IS NOT NULL AND ORD_FINCA_ESPEC IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(NUM_MUN_SGAB)),TO_VARCHAR(TRY_TO_NUMBER(NUM_CARRER)),UPPER(TRIM(NUM_INI_FINCA)),COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_INI_FINCA)),''),'^^'),UPPER(TRIM(NUM_FIN_FINCA)),COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_FIN_FINCA)),''),'^^'),UPPER(TRIM(SIT_FINCA_ESPEC)),UPPER(TRIM(ORD_FINCA_ESPEC))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(NUM_MUN_SGAB),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_CARRER) IS NOT NULL AND NULLIF(TRIM(NUM_INI_FINCA),'') IS NOT NULL AND NULLIF(TRIM(NUM_FIN_FINCA),'') IS NOT NULL AND SIT_FINCA_ESPEC IS NOT NULL AND ORD_FINCA_ESPEC IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_finca') }}

    UNION ALL

SELECT 'RAMAL' AS OBJECT_NAME, 'raw_ramal' AS RAW_MODEL, 'l4_ramal' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_RAMAL),'') IS NOT NULL, UPPER(TRIM(POLISSA_RAMAL)), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_RAMAL),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_ramal') }}

    UNION ALL

SELECT 'SUBMIN_SERVEI' AS OBJECT_NAME, 'raw_submin_servei' AS RAW_MODEL, 'l4_submin_servei' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL, UPPER(TRIM(POLISSA_SUBM)), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_submin_servei') }}

    UNION ALL

SELECT 'SUBMIN_IAE' AS OBJECT_NAME, 'raw_submin_iae' AS RAW_MODEL, 'l4_submin_iae' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND NULLIF(TRIM(SECCIO),'') IS NOT NULL AND NULLIF(TRIM(EPIGRAF_IAE),'') IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),UPPER(TRIM(SECCIO)),UPPER(TRIM(EPIGRAF_IAE))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND NULLIF(TRIM(SECCIO),'') IS NOT NULL AND NULLIF(TRIM(EPIGRAF_IAE),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_submin_iae') }}

    UNION ALL

SELECT 'PADRO_TRR' AS OBJECT_NAME, 'raw_padro_trr' AS RAW_MODEL, 'l4_padro_trr' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND TRY_TO_TIMESTAMP(TS_PADRO_TRR) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),TO_VARCHAR(TRY_TO_TIMESTAMP(TS_PADRO_TRR),'YYYY-MM-DD HH24:MI:SS.FF9')), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND TRY_TO_TIMESTAMP(TS_PADRO_TRR) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_padro_trr') }}

    UNION ALL

SELECT 'PADRO_TAMGREM' AS OBJECT_NAME, 'raw_padro_tamgrem' AS RAW_MODEL, 'l4_padro_tamgrem' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND TRY_TO_TIMESTAMP(TS_PADRO_TAMGREM) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),TO_VARCHAR(TRY_TO_TIMESTAMP(TS_PADRO_TAMGREM),'YYYY-MM-DD HH24:MI:SS.FF9')), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND TRY_TO_TIMESTAMP(TS_PADRO_TAMGREM) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_padro_tamgrem') }}

    UNION ALL

SELECT 'HIST_SS_PE' AS OBJECT_NAME, 'raw_hist_ss_pe' AS RAW_MODEL, 'l4_hist_ss_pe' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND NULLIF(TRIM(TIP_COLECTIVO),'') IS NOT NULL AND TRY_TO_TIMESTAMP(TS_MOM_IND) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),UPPER(TRIM(TIP_COLECTIVO)),TO_VARCHAR(TRY_TO_TIMESTAMP(TS_MOM_IND),'YYYY-MM-DD HH24:MI:SS.FF9')), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND NULLIF(TRIM(TIP_COLECTIVO),'') IS NOT NULL AND TRY_TO_TIMESTAMP(TS_MOM_IND) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_hist_ss_pe') }}

    UNION ALL

SELECT 'SERVEI_EQ_CI' AS OBJECT_NAME, 'raw_servei_eq_ci' AS RAW_MODEL, 'l4_servei_eq_ci' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL, UPPER(TRIM(POLISSA_SUBM)), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_servei_eq_ci') }}

    UNION ALL

SELECT 'SERVEI_FACTURAR' AS OBJECT_NAME, 'raw_servei_facturar' AS RAW_MODEL, 'l4_servei_facturar' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND TRY_TO_DATE(DATA_FIN_FACT) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),TO_VARCHAR(TRY_TO_DATE(DATA_FIN_FACT),'YYYY-MM-DD')), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL AND TRY_TO_DATE(DATA_FIN_FACT) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_servei_facturar') }}

    UNION ALL

SELECT 'CONVENI_FRAU' AS OBJECT_NAME, 'raw_conveni_frau' AS RAW_MODEL, 'l4_conveni_frau' AS L4_MODEL, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL, UPPER(TRIM(POLISSA_SUBM)), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(POLISSA_SUBM),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_conveni_frau') }}

    UNION ALL

SELECT 'FACT_RESUM' AS OBJECT_NAME, 'raw_fact_resum' AS RAW_MODEL, 'l4_fact_resum' AS L4_MODEL, IFF(NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(TRY_TO_NUMBER(NUM_FACTURA))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_fact_resum') }}

    UNION ALL

SELECT 'FACT_AIGUA' AS OBJECT_NAME, 'raw_fact_aigua' AS RAW_MODEL, 'l4_fact_aigua' AS L4_MODEL, IFF(TRY_TO_NUMBER(NUM_PARTICIO) IS NOT NULL AND NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL, CONCAT_WS('|',TO_VARCHAR(TRY_TO_NUMBER(NUM_PARTICIO)),UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(TRY_TO_NUMBER(NUM_FACTURA))), NULL) AS BUSINESS_KEY, IFF(TRY_TO_NUMBER(NUM_PARTICIO) IS NOT NULL AND NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_fact_aigua') }}

    UNION ALL

SELECT 'FACT_CONCEPTE' AS OBJECT_NAME, 'raw_fact_concepte' AS RAW_MODEL, 'l4_fact_concepte' AS L4_MODEL, IFF(TRY_TO_NUMBER(NUM_PARTICIO) IS NOT NULL AND NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL AND TRY_TO_NUMBER(NUM_LINEA) IS NOT NULL AND NULLIF(TRIM(NUM_CONCEPTE),'') IS NOT NULL, CONCAT_WS('|',TO_VARCHAR(TRY_TO_NUMBER(NUM_PARTICIO)),UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(TRY_TO_NUMBER(NUM_FACTURA)),TO_VARCHAR(TRY_TO_NUMBER(NUM_LINEA)),UPPER(TRIM(NUM_CONCEPTE))), NULL) AS BUSINESS_KEY, IFF(TRY_TO_NUMBER(NUM_PARTICIO) IS NOT NULL AND NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL AND TRY_TO_NUMBER(NUM_LINEA) IS NOT NULL AND NULLIF(TRIM(NUM_CONCEPTE),'') IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_fact_concepte') }}

    UNION ALL

SELECT 'FACT_REGUL' AS OBJECT_NAME, 'raw_fact_regul' AS RAW_MODEL, 'l4_fact_regul' AS L4_MODEL, IFF(NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL AND TRY_TO_DATE(DATA_FIN_PER_INCID) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(TRY_TO_NUMBER(NUM_FACTURA)),TO_VARCHAR(TRY_TO_DATE(DATA_FIN_PER_INCID),'YYYY-MM-DD')), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL AND TRY_TO_DATE(DATA_FIN_PER_INCID) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_fact_regul') }}

    UNION ALL

SELECT 'FACT_RECUP' AS OBJECT_NAME, 'raw_fact_recup' AS RAW_MODEL, 'l4_fact_recup' AS L4_MODEL, IFF(NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(TRY_TO_NUMBER(NUM_FACTURA))), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_fact_recup') }}

    UNION ALL

SELECT 'SITUACIO_FACT' AS OBJECT_NAME, 'raw_situacio_fact' AS RAW_MODEL, 'l4_situacio_fact' AS L4_MODEL, IFF(TRY_TO_NUMBER(NUM_PARTICIO) IS NOT NULL AND NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL AND TRY_TO_TIMESTAMP(MOM_SIT_FACT) IS NOT NULL, CONCAT_WS('|',TO_VARCHAR(TRY_TO_NUMBER(NUM_PARTICIO)),UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(TRY_TO_NUMBER(NUM_FACTURA)),TO_VARCHAR(TRY_TO_TIMESTAMP(MOM_SIT_FACT),'YYYY-MM-DD HH24:MI:SS.FF9')), NULL) AS BUSINESS_KEY, IFF(TRY_TO_NUMBER(NUM_PARTICIO) IS NOT NULL AND NULLIF(TRIM(ID_EMPRESA),'') IS NOT NULL AND NULLIF(TRIM(ANY_FACTURA),'') IS NOT NULL AND TRY_TO_NUMBER(NUM_FACTURA) IS NOT NULL AND TRY_TO_TIMESTAMP(MOM_SIT_FACT) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_situacio_fact') }}

    UNION ALL

SELECT 'TARIFA_FACTURACIO' AS OBJECT_NAME, 'raw_tarifa_facturacio' AS RAW_MODEL, 'l4_tarifa_facturacio' AS L4_MODEL, IFF(NULLIF(TRIM(TIP_TARIFA),'') IS NOT NULL AND NULLIF(TRIM(SUBTIP_TARIFA),'') IS NOT NULL AND TRY_TO_DATE(DATA_INI_VIGENCIA) IS NOT NULL, CONCAT_WS('|',UPPER(TRIM(TIP_TARIFA)),UPPER(TRIM(SUBTIP_TARIFA)),TO_VARCHAR(TRY_TO_DATE(DATA_INI_VIGENCIA),'YYYY-MM-DD')), NULL) AS BUSINESS_KEY, IFF(NULLIF(TRIM(TIP_TARIFA),'') IS NOT NULL AND NULLIF(TRIM(SUBTIP_TARIFA),'') IS NOT NULL AND TRY_TO_DATE(DATA_INI_VIGENCIA) IS NOT NULL, TRUE, FALSE) AS IS_VALID_KEY FROM {{ source('raw_sicab', 'raw_tarifa_facturacio') }}

),

l4_key_rows AS (

    SELECT 'CODIFICACIONS' AS OBJECT_NAME, 'raw_codificacions' AS RAW_MODEL, 'l4_codificacions' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(TIP_CODI)),UPPER(TRIM(CLAU_CODI))) AS BUSINESS_KEY FROM {{ ref('l4_codificacions') }} WHERE TIP_CODI IS NOT NULL AND CLAU_CODI IS NOT NULL

    UNION ALL

SELECT 'MUNICIPI_SGAB' AS OBJECT_NAME, 'raw_municipi_sgab' AS RAW_MODEL, 'l4_municipi_sgab' AS L4_MODEL, UPPER(TRIM(NUM_MUN_SGAB)) AS BUSINESS_KEY FROM {{ ref('l4_municipi_sgab') }} WHERE NUM_MUN_SGAB IS NOT NULL

    UNION ALL

SELECT 'DTE_MUNICIPAL' AS OBJECT_NAME, 'raw_dte_municipal' AS RAW_MODEL, 'l4_dte_municipal' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(NUM_MUN_SGAB)),UPPER(TRIM(NUM_DTE_MUNI))) AS BUSINESS_KEY FROM {{ ref('l4_dte_municipal') }} WHERE NUM_MUN_SGAB IS NOT NULL AND NUM_DTE_MUNI IS NOT NULL

    UNION ALL

SELECT 'EPIGRAF_IAE' AS OBJECT_NAME, 'raw_epigraf_iae' AS RAW_MODEL, 'l4_epigraf_iae' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(SECCIO)),UPPER(TRIM(EPIGRAF_IAE))) AS BUSINESS_KEY FROM {{ ref('l4_epigraf_iae') }} WHERE SECCIO IS NOT NULL AND EPIGRAF_IAE IS NOT NULL

    UNION ALL

SELECT 'CARRER' AS OBJECT_NAME, 'raw_carrer' AS RAW_MODEL, 'l4_carrer' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(NUM_MUN_SGAB)),TO_VARCHAR(NUM_CARRER)) AS BUSINESS_KEY FROM {{ ref('l4_carrer') }} WHERE NUM_MUN_SGAB IS NOT NULL AND NUM_CARRER IS NOT NULL

    UNION ALL

SELECT 'FINCA' AS OBJECT_NAME, 'raw_finca' AS RAW_MODEL, 'l4_finca' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(NUM_MUN_SGAB)),TO_VARCHAR(NUM_CARRER),UPPER(TRIM(NUM_INI_FINCA)),COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_INI_FINCA)),''),'^^'),UPPER(TRIM(NUM_FIN_FINCA)),COALESCE(NULLIF(UPPER(TRIM(COMP_NUM_FIN_FINCA)),''),'^^'),UPPER(TRIM(SIT_FINCA_ESPEC)),UPPER(TRIM(ORD_FINCA_ESPEC))) AS BUSINESS_KEY FROM {{ ref('l4_finca') }} WHERE NUM_MUN_SGAB IS NOT NULL AND NUM_CARRER IS NOT NULL AND NUM_INI_FINCA IS NOT NULL AND NUM_FIN_FINCA IS NOT NULL AND SIT_FINCA_ESPEC IS NOT NULL AND ORD_FINCA_ESPEC IS NOT NULL

    UNION ALL

SELECT 'RAMAL' AS OBJECT_NAME, 'raw_ramal' AS RAW_MODEL, 'l4_ramal' AS L4_MODEL, UPPER(TRIM(POLISSA_RAMAL)) AS BUSINESS_KEY FROM {{ ref('l4_ramal') }} WHERE POLISSA_RAMAL IS NOT NULL

    UNION ALL

SELECT 'SUBMIN_SERVEI' AS OBJECT_NAME, 'raw_submin_servei' AS RAW_MODEL, 'l4_submin_servei' AS L4_MODEL, UPPER(TRIM(POLISSA_SUBM)) AS BUSINESS_KEY FROM {{ ref('l4_submin_servei') }} WHERE POLISSA_SUBM IS NOT NULL

    UNION ALL

SELECT 'SUBMIN_IAE' AS OBJECT_NAME, 'raw_submin_iae' AS RAW_MODEL, 'l4_submin_iae' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),UPPER(TRIM(SECCIO)),UPPER(TRIM(EPIGRAF_IAE))) AS BUSINESS_KEY FROM {{ ref('l4_submin_iae') }} WHERE POLISSA_SUBM IS NOT NULL AND SECCIO IS NOT NULL AND EPIGRAF_IAE IS NOT NULL

    UNION ALL

SELECT 'PADRO_TRR' AS OBJECT_NAME, 'raw_padro_trr' AS RAW_MODEL, 'l4_padro_trr' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),TO_VARCHAR(TS_PADRO_TRR,'YYYY-MM-DD HH24:MI:SS.FF9')) AS BUSINESS_KEY FROM {{ ref('l4_padro_trr') }} WHERE POLISSA_SUBM IS NOT NULL AND TS_PADRO_TRR IS NOT NULL

    UNION ALL

SELECT 'PADRO_TAMGREM' AS OBJECT_NAME, 'raw_padro_tamgrem' AS RAW_MODEL, 'l4_padro_tamgrem' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),TO_VARCHAR(TS_PADRO_TAMGREM,'YYYY-MM-DD HH24:MI:SS.FF9')) AS BUSINESS_KEY FROM {{ ref('l4_padro_tamgrem') }} WHERE POLISSA_SUBM IS NOT NULL AND TS_PADRO_TAMGREM IS NOT NULL

    UNION ALL

SELECT 'HIST_SS_PE' AS OBJECT_NAME, 'raw_hist_ss_pe' AS RAW_MODEL, 'l4_hist_ss_pe' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),UPPER(TRIM(TIP_COLECTIVO)),TO_VARCHAR(TS_MOM_IND,'YYYY-MM-DD HH24:MI:SS.FF9')) AS BUSINESS_KEY FROM {{ ref('l4_hist_ss_pe') }} WHERE POLISSA_SUBM IS NOT NULL AND TIP_COLECTIVO IS NOT NULL AND TS_MOM_IND IS NOT NULL

    UNION ALL

SELECT 'SERVEI_EQ_CI' AS OBJECT_NAME, 'raw_servei_eq_ci' AS RAW_MODEL, 'l4_servei_eq_ci' AS L4_MODEL, UPPER(TRIM(POLISSA_SUBM)) AS BUSINESS_KEY FROM {{ ref('l4_servei_eq_ci') }} WHERE POLISSA_SUBM IS NOT NULL

    UNION ALL

SELECT 'SERVEI_FACTURAR' AS OBJECT_NAME, 'raw_servei_facturar' AS RAW_MODEL, 'l4_servei_facturar' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(POLISSA_SUBM)),TO_VARCHAR(DATA_FIN_FACT,'YYYY-MM-DD')) AS BUSINESS_KEY FROM {{ ref('l4_servei_facturar') }} WHERE POLISSA_SUBM IS NOT NULL AND DATA_FIN_FACT IS NOT NULL

    UNION ALL

SELECT 'CONVENI_FRAU' AS OBJECT_NAME, 'raw_conveni_frau' AS RAW_MODEL, 'l4_conveni_frau' AS L4_MODEL, UPPER(TRIM(POLISSA_SUBM)) AS BUSINESS_KEY FROM {{ ref('l4_conveni_frau') }} WHERE POLISSA_SUBM IS NOT NULL

    UNION ALL

SELECT 'FACT_RESUM' AS OBJECT_NAME, 'raw_fact_resum' AS RAW_MODEL, 'l4_fact_resum' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(NUM_FACTURA)) AS BUSINESS_KEY FROM {{ ref('l4_fact_resum') }} WHERE ID_EMPRESA IS NOT NULL AND ANY_FACTURA IS NOT NULL AND NUM_FACTURA IS NOT NULL

    UNION ALL

SELECT 'FACT_AIGUA' AS OBJECT_NAME, 'raw_fact_aigua' AS RAW_MODEL, 'l4_fact_aigua' AS L4_MODEL, CONCAT_WS('|',TO_VARCHAR(NUM_PARTICIO),UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(NUM_FACTURA)) AS BUSINESS_KEY FROM {{ ref('l4_fact_aigua') }} WHERE NUM_PARTICIO IS NOT NULL AND ID_EMPRESA IS NOT NULL AND ANY_FACTURA IS NOT NULL AND NUM_FACTURA IS NOT NULL

    UNION ALL

SELECT 'FACT_CONCEPTE' AS OBJECT_NAME, 'raw_fact_concepte' AS RAW_MODEL, 'l4_fact_concepte' AS L4_MODEL, CONCAT_WS('|',TO_VARCHAR(NUM_PARTICIO),UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(NUM_FACTURA),TO_VARCHAR(NUM_LINEA),UPPER(TRIM(NUM_CONCEPTE))) AS BUSINESS_KEY FROM {{ ref('l4_fact_concepte') }} WHERE NUM_PARTICIO IS NOT NULL AND ID_EMPRESA IS NOT NULL AND ANY_FACTURA IS NOT NULL AND NUM_FACTURA IS NOT NULL AND NUM_LINEA IS NOT NULL AND NUM_CONCEPTE IS NOT NULL

    UNION ALL

SELECT 'FACT_REGUL' AS OBJECT_NAME, 'raw_fact_regul' AS RAW_MODEL, 'l4_fact_regul' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(NUM_FACTURA),TO_VARCHAR(DATA_FIN_PER_INCID,'YYYY-MM-DD')) AS BUSINESS_KEY FROM {{ ref('l4_fact_regul') }} WHERE ID_EMPRESA IS NOT NULL AND ANY_FACTURA IS NOT NULL AND NUM_FACTURA IS NOT NULL AND DATA_FIN_PER_INCID IS NOT NULL

    UNION ALL

SELECT 'FACT_RECUP' AS OBJECT_NAME, 'raw_fact_recup' AS RAW_MODEL, 'l4_fact_recup' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(NUM_FACTURA)) AS BUSINESS_KEY FROM {{ ref('l4_fact_recup') }} WHERE ID_EMPRESA IS NOT NULL AND ANY_FACTURA IS NOT NULL AND NUM_FACTURA IS NOT NULL

    UNION ALL

SELECT 'SITUACIO_FACT' AS OBJECT_NAME, 'raw_situacio_fact' AS RAW_MODEL, 'l4_situacio_fact' AS L4_MODEL, CONCAT_WS('|',TO_VARCHAR(NUM_PARTICIO),UPPER(TRIM(ID_EMPRESA)),UPPER(TRIM(ANY_FACTURA)),TO_VARCHAR(NUM_FACTURA),TO_VARCHAR(MOM_SIT_FACT,'YYYY-MM-DD HH24:MI:SS.FF9')) AS BUSINESS_KEY FROM {{ ref('l4_situacio_fact') }} WHERE NUM_PARTICIO IS NOT NULL AND ID_EMPRESA IS NOT NULL AND ANY_FACTURA IS NOT NULL AND NUM_FACTURA IS NOT NULL AND MOM_SIT_FACT IS NOT NULL

    UNION ALL

SELECT 'TARIFA_FACTURACIO' AS OBJECT_NAME, 'raw_tarifa_facturacio' AS RAW_MODEL, 'l4_tarifa_facturacio' AS L4_MODEL, CONCAT_WS('|',UPPER(TRIM(TIP_TARIFA)),UPPER(TRIM(SUBTIP_TARIFA)),TO_VARCHAR(DATA_INI_VIGENCIA,'YYYY-MM-DD')) AS BUSINESS_KEY FROM {{ ref('l4_tarifa_facturacio') }} WHERE TIP_TARIFA IS NOT NULL AND SUBTIP_TARIFA IS NOT NULL AND DATA_INI_VIGENCIA IS NOT NULL

),

raw_valid_keys AS (

    SELECT DISTINCT OBJECT_NAME, RAW_MODEL, L4_MODEL, BUSINESS_KEY
    FROM raw_key_rows
    WHERE IS_VALID_KEY

),

l4_valid_keys AS (

    SELECT DISTINCT OBJECT_NAME, RAW_MODEL, L4_MODEL, BUSINESS_KEY
    FROM l4_key_rows

),

count_issues AS (

    SELECT
        'COUNT_MISMATCH' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        OBJECT_NAME,
        RAW_MODEL,
        L4_MODEL,
        CAST(NULL AS VARCHAR) AS BUSINESS_KEY,
        RAW_COUNT AS VALUE_RAW,
        L4_COUNT AS VALUE_L4,
        L4_COUNT - RAW_COUNT AS DIFFERENCE,
        'El numero total de filas difiere entre RAW y L4' AS DETAIL
    FROM row_counts
    WHERE RAW_COUNT <> L4_COUNT

),

invalid_raw_keys AS (

    SELECT
        'INVALID_RAW_KEY' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        OBJECT_NAME,
        RAW_MODEL,
        L4_MODEL,
        CAST(NULL AS VARCHAR) AS BUSINESS_KEY,
        COUNT(*) AS VALUE_RAW,
        0 AS VALUE_L4,
        -COUNT(*) AS DIFFERENCE,
        'Filas RAW con clave natural nula, vacia o no convertible al tipo L4' AS DETAIL
    FROM raw_key_rows
    WHERE NOT IS_VALID_KEY
    GROUP BY OBJECT_NAME, RAW_MODEL, L4_MODEL

),

raw_duplicate_keys AS (

    SELECT
        'DUPLICATE_RAW_KEY' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        OBJECT_NAME,
        RAW_MODEL,
        L4_MODEL,
        BUSINESS_KEY,
        COUNT(*) AS VALUE_RAW,
        1 AS VALUE_L4,
        1 - COUNT(*) AS DIFFERENCE,
        'Clave natural repetida en RAW' AS DETAIL
    FROM raw_key_rows
    WHERE IS_VALID_KEY
    GROUP BY OBJECT_NAME, RAW_MODEL, L4_MODEL, BUSINESS_KEY
    HAVING COUNT(*) > 1

),

l4_duplicate_keys AS (

    SELECT
        'DUPLICATE_L4_KEY' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        OBJECT_NAME,
        RAW_MODEL,
        L4_MODEL,
        BUSINESS_KEY,
        1 AS VALUE_RAW,
        COUNT(*) AS VALUE_L4,
        COUNT(*) - 1 AS DIFFERENCE,
        'Clave natural repetida en L4' AS DETAIL
    FROM l4_key_rows
    GROUP BY OBJECT_NAME, RAW_MODEL, L4_MODEL, BUSINESS_KEY
    HAVING COUNT(*) > 1

),

missing_in_l4 AS (

    SELECT
        'MISSING_IN_L4' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        r.OBJECT_NAME,
        r.RAW_MODEL,
        r.L4_MODEL,
        r.BUSINESS_KEY,
        1 AS VALUE_RAW,
        0 AS VALUE_L4,
        -1 AS DIFFERENCE,
        'Clave natural valida presente en RAW y ausente en L4' AS DETAIL
    FROM raw_valid_keys AS r
    LEFT JOIN l4_valid_keys AS l
        ON l.OBJECT_NAME = r.OBJECT_NAME
       AND l.BUSINESS_KEY = r.BUSINESS_KEY
    WHERE l.BUSINESS_KEY IS NULL

),

unexpected_in_l4 AS (

    SELECT
        'UNEXPECTED_IN_L4' AS CONTROL_TYPE,
        'ERROR' AS SEVERITY,
        l.OBJECT_NAME,
        l.RAW_MODEL,
        l.L4_MODEL,
        l.BUSINESS_KEY,
        0 AS VALUE_RAW,
        1 AS VALUE_L4,
        1 AS DIFFERENCE,
        'Clave natural presente en L4 y ausente en la imagen RAW' AS DETAIL
    FROM l4_valid_keys AS l
    LEFT JOIN raw_valid_keys AS r
        ON r.OBJECT_NAME = l.OBJECT_NAME
       AND r.BUSINESS_KEY = l.BUSINESS_KEY
    WHERE r.BUSINESS_KEY IS NULL

)

SELECT * FROM count_issues
UNION ALL
SELECT * FROM invalid_raw_keys
UNION ALL
SELECT * FROM raw_duplicate_keys
UNION ALL
SELECT * FROM l4_duplicate_keys
UNION ALL
SELECT * FROM missing_in_l4
UNION ALL
SELECT * FROM unexpected_in_l4
