{{ config(materialized='table', schema='gold_fact', tags=['gold_fact','fact']) }}
select
    c.HK_FACTURA_CONCEPTO,c.HK_FACTURA,
    coalesce(c.HK_SUBMIN_SERVEI,sha2_hex('DESCONOCIDO',256)) as HK_SUBMIN_SERVEI,
    coalesce(c.HK_TIPO_SUMINISTRO,sha2_hex('DESCONOCIDO',256)) as HK_TIPO_SUMINISTRO,
    coalesce(c.HK_CONCEPTO,sha2_hex('DESCONOCIDO',256)) as HK_CONCEPTO,
    c.TABLA_ORIGEN as ORIGEN_CONCEPTO,
    c.NUM_PARTICIO,c.ID_EMPRESA,c.ANY_FACTURA,c.NUM_FACTURA,c.NUM_LINEA,c.NUM_CONCEPTO,c.DESC_CONCEPTO,
    c.POLISSA_SUBM,c.DATA_INI_FACT,c.DATA_FIN_FACT,c.DATA_EMISS_FACT,c.COD_TIPO_SUMINISTRO_FACTURA,
    c.CANTIDAD,c.UNIDAD_MEDIDA,c.BASE_CALCULO,c.TIPO_TASA,c.PRECIO_UNITARIO,c.PORCENTAJE,c.IMP_CONCEPTO,c.IVA_APLICADO,
    c.ID_CARGA,c.FECHA_EXTRACCION,convert_timezone('Europe/Madrid',current_timestamp()) FECHA_CARGA,c.SISTEMA_ORIGEN,'S_FACTURA_CONCEPTO' TABLA_ORIGEN
from {{ ref('s_factura_concepto') }} c
