{{ config(materialized='table', schema='gold_fact', tags=['gold_fact','fact']) }}
select c.HK_FACTURA_CONCEPTE,c.HK_FACTURA,coalesce(c.HK_SUBMIN_SERVEI,sha2_hex('SUMINISTRO|DESCONOCIDO',256)) HK_SUBMIN_SERVEI,
       case when c.TABLA_ORIGEN='L4_FACT_AIGUA' and c.TIPUS_CONCEPTE is not null then 'AIGUA:'||c.TIPUS_CONCEPTE
            when c.TABLA_ORIGEN='L4_FACT_CONCEPTE' and c.NUM_CONCEPTE is not null then 'CONCEPTE:'||c.NUM_CONCEPTE
            else 'DESCONOCIDO' end CODIGO_CONCEPTO,
       c.TABLA_ORIGEN as ORIGEN_CONCEPTO,
       c.NUM_PARTICIO,c.ID_EMPRESA,c.ANY_FACTURA,c.NUM_FACTURA,c.NUM_LINEA,c.TIPUS_CONCEPTE,c.NUM_CONCEPTE,c.DESC_CONCEPTE,
       c.POLISSA_SUBM,c.DATA_INI_FACT,c.DATA_FIN_FACT,c.DATA_EMISS_FACT,c.TIP_SUBM_SERV as TIP_SUBM_SERV_FACTURA,
       c.QUANTITAT,c.UNITAT_MESURA,c.BASE_CALCUL,c.TIP_TAXA,c.PREU_UNITARI,c.PERCENTATGE,c.IMP_CONCEPTE,c.IVA_APLICAT,
       c.ID_CARGA,c.FECHA_EXTRACCION,convert_timezone('Europe/Madrid',current_timestamp()) FECHA_CARGA,c.SISTEMA_ORIGEN,'S_FACTURA_CONCEPTO' TABLA_ORIGEN
from {{ ref('s_factura_concepto') }} c
