{{ config(materialized='table', schema='gold_fact', tags=['gold_fact','fact']) }}
select HK_FACTURA_SITUACION,HK_FACTURA,coalesce(HK_SITUACION_FACT,sha2_hex('SITUACION|DESCONOCIDA',256)) HK_SITUACION_FACT,
       NUM_PARTICIO,ID_EMPRESA,ANY_FACTURA,NUM_FACTURA,MOM_INI_SITUACION,MOM_FIN_SITUACION,NUM_ORDEN_SITUACION,ES_SITUACION_ACTUAL,
       TIP_SIT_FACT,DESC_SITUACION,DESC_BREU_SITUACION,CAUSA_SIT_FACT,
       ID_CARGA,FECHA_EXTRACCION,convert_timezone('Europe/Madrid',current_timestamp()) FECHA_CARGA,SISTEMA_ORIGEN,'S_FACTURA_SITUACION_HIST' TABLA_ORIGEN
from {{ ref('s_factura_situacion_hist') }}
