{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key=['NUM_MUN_SGAB', 'NUM_CARRER', 'NUM_INI_FINCA', 'COMP_NUM_INI_FINCA', 'NUM_FIN_FINCA', 'COMP_NUM_FIN_FINCA', 'SIT_FINCA_ESPEC', 'ORD_FINCA_ESPEC'],
    schema='l4_fact',
    tags=['l4_fact', 'l4', 'bronze']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_finca') }}
)

select
    COALESCE(NULLIF(TRIM(raw."NUM_MUN_SGAB"), ''), '^^') AS NUM_MUN_SGAB,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_CARRER"), ''), 6, 0), 0) AS NUM_CARRER,
    COALESCE(NULLIF(TRIM(raw."NUM_INI_FINCA"), ''), '^^') AS NUM_INI_FINCA,
    NULLIF(TRIM(raw."COMP_NUM_INI_FINCA"), '') AS COMP_NUM_INI_FINCA,
    COALESCE(NULLIF(TRIM(raw."NUM_FIN_FINCA"), ''), '^^') AS NUM_FIN_FINCA,
    NULLIF(TRIM(raw."COMP_NUM_FIN_FINCA"), '') AS COMP_NUM_FIN_FINCA,
    COALESCE(NULLIF(TRIM(raw."SIT_FINCA_ESPEC"), ''), '^^') AS SIT_FINCA_ESPEC,
    COALESCE(NULLIF(TRIM(raw."ORD_FINCA_ESPEC"), ''), '^^') AS ORD_FINCA_ESPEC,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_TORN_LECT_MENS"), ''), 4, 0), 0) AS NUM_TORN_LECT_MENS,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."ORD_FINCA_TORN_MEN"), ''), 3, 0), 0) AS ORD_FINCA_TORN_MEN,
    COALESCE(NULLIF(TRIM(raw."NUM_DTE_POST_FINCA"), ''), '^^') AS NUM_DTE_POST_FINCA,
    COALESCE(NULLIF(TRIM(raw."ESTAT_FINCA"), ''), '^^') AS ESTAT_FINCA,
    COALESCE(NULLIF(TRIM(raw."ID_GRUP_ELEV_FINCA"), ''), '^^') AS ID_GRUP_ELEV_FINCA,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."PRES_XARXA_FINCA"), ''), 3, 0), 0) AS PRES_XARXA_FINCA,
    COALESCE(NULLIF(TRIM(raw."CAT_FISCAL_FINCA"), ''), '^^') AS CAT_FISCAL_FINCA,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."ALTURA_FINCA"), ''), 3, 0), 0) AS ALTURA_FINCA,
    COALESCE(NULLIF(TRIM(raw."ID_FINCA_RENDA_LIM"), ''), '^^') AS ID_FINCA_RENDA_LIM,
    COALESCE(NULLIF(TRIM(raw."NUM_EXP_RENDA_LIM"), ''), '^^') AS NUM_EXP_RENDA_LIM,
    COALESCE(NULLIF(TRIM(raw."NUM_ZONA_RECOR"), ''), '^^') AS NUM_ZONA_RECOR,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_TRAVES"), ''), 7, 0), 0) AS NUM_TRAVES,
    COALESCE(NULLIF(TRIM(raw."CASA_RECOR_PERIOD"), ''), '^^') AS CASA_RECOR_PERIOD,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_NUS_XARXA"), ''), 5, 0), 0) AS NUM_NUS_XARXA,
    NULLIF(TRIM(raw."ID_LOT_LECT"), '') AS ID_LOT_LECT,
    COALESCE(NULLIF(TRIM(raw."OBS_ADRE_INCOMPLET"), ''), '^^') AS OBS_ADRE_INCOMPLET,
    COALESCE(NULLIF(TRIM(raw."PARTICULARIT_FINCA"), ''), '^^') AS PARTICULARIT_FINCA,
    COALESCE(NULLIF(TRIM(raw."LOCAL_CLAUS_FINCA"), ''), '^^') AS LOCAL_CLAUS_FINCA,
    COALESCE(NULLIF(TRIM(raw."QL_COMPT_ELECTRON"), ''), '^^') AS QL_COMPT_ELECTRON,
    COALESCE(NULLIF(TRIM(raw."NUM_DTE_MUNI_FINCA"), ''), '^^') AS NUM_DTE_MUNI_FINCA,
    COALESCE(NULLIF(TRIM(raw."QL_BATERIA_CABLE"), ''), '^^') AS QL_BATERIA_CABLE,
    NULLIF(TRIM(raw."CODI_UBICACIO_SAP"), '') AS CODI_UBICACIO_SAP,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_TZ, '{{ run_started_at.isoformat() }}'::TIMESTAMP_TZ) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP()) AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_FINCA' AS TABLA_ORIGEN
from raw
