{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key=['POLISSA_SUBM', 'TS_PADRO_TAMGREM'],
    schema='l4_fact',
    tags=['l4_fact', 'l4', 'bronze']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_padro_tamgrem') }}
)

select
    COALESCE(NULLIF(TRIM(raw."POLISSA_SUBM"), ''), '^^') AS POLISSA_SUBM,
    COALESCE(TRY_TO_TIMESTAMP_NTZ(NULLIF(TRIM(raw."TS_PADRO_TAMGREM"), '')), '0001-01-01 00:00:00.000'::TIMESTAMP_NTZ) AS TS_PADRO_TAMGREM,
    COALESCE(NULLIF(TRIM(raw."TIP_TAXA_TAMGREM"), ''), '^^') AS TIP_TAXA_TAMGREM,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_HABIT_SUBM"), ''), 3, 0), 0) AS NOMB_HABIT_SUBM,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."CONSUM_MES_BASE"), ''), 7, 0), 0) AS CONSUM_MES_BASE,
    COALESCE(NULLIF(TRIM(raw."TIP_QUOTA_TAMGREM"), ''), '^^') AS TIP_QUOTA_TAMGREM,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."CONSUM_MIG_DIA"), ''), 9, 4), 0) AS CONSUM_MIG_DIA,
    COALESCE(NULLIF(TRIM(raw."NUMERO_EMPLEAT"), ''), '^^') AS NUMERO_EMPLEAT,
    COALESCE(NULLIF(TRIM(raw."SECCIO"), ''), '^^') AS SECCIO,
    COALESCE(NULLIF(TRIM(raw."EPIGRAF_IAE"), ''), '^^') AS EPIGRAF_IAE,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."PERC_BONIF_TAMGREM"), ''), 5, 2), 0) AS PERC_BONIF_TAMGREM,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."IMP_CUOTA"), ''), 11, 2), 0) AS IMP_CUOTA,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."SUPERFICIE_REAL"), ''), 7, 0), 0) AS SUPERFICIE_REAL,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."SUPERFICIE_POND"), ''), 9, 2), 0) AS SUPERFICIE_POND,
    COALESCE(NULLIF(TRIM(raw."NIV_GEN_RES"), ''), '^^') AS NIV_GEN_RES,
    COALESCE(NULLIF(TRIM(raw."COD_GEN_RES"), ''), '^^') AS COD_GEN_RES,
    COALESCE(NULLIF(TRIM(raw."ORIGEN"), ''), '^^') AS ORIGEN,
    COALESCE(NULLIF(TRIM(raw."ID_BONIF_DECGER"), ''), '^^') AS ID_BONIF_DECGER,
    COALESCE(NULLIF(TRIM(raw."ID_LIMIT"), ''), '^^') AS ID_LIMIT,
    COALESCE(NULLIF(TRIM(raw."SUBTIP_TAXA_TAMGREM"), ''), '^^') AS SUBTIP_TAXA_TAMGREM,
    COALESCE(NULLIF(TRIM(raw."OBSERVACIONS"), ''), '^^') AS OBSERVACIONS,
    COALESCE(TRY_TO_TIMESTAMP_NTZ(NULLIF(TRIM(raw."TS_ALTA"), '')), '0001-01-01 00:00:00.000'::TIMESTAMP_NTZ) AS TS_ALTA,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_TZ, '{{ run_started_at.isoformat() }}'::TIMESTAMP_TZ) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP()) AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_PADRO_TAMGREM' AS TABLA_ORIGEN
from raw
