{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key=['POLISSA_RAMAL'],
    schema='l4_fact',
    tags=['l4_fact', 'l4', 'bronze']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_ramal') }}
)

select
    COALESCE(NULLIF(TRIM(raw."POLISSA_RAMAL"), ''), '^^') AS POLISSA_RAMAL,
    COALESCE(NULLIF(TRIM(raw."DVER_POLISSA_RAMAL"), ''), '^^') AS DVER_POLISSA_RAMAL,
    COALESCE(NULLIF(TRIM(raw."SIT_RAMAL"), ''), '^^') AS SIT_RAMAL,
    COALESCE(NULLIF(TRIM(raw."TIP_OPER_RAMAL"), ''), '^^') AS TIP_OPER_RAMAL,
    COALESCE(NULLIF(TRIM(raw."US_RAMAL"), ''), '^^') AS US_RAMAL,
    COALESCE(NULLIF(TRIM(raw."MATERIAL_RAMAL"), ''), '^^') AS MATERIAL_RAMAL,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_INST_RAMAL"), '')), '0001-01-01'::DATE) AS DATA_INST_RAMAL,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."DIAMETRE_RAMAL"), ''), 3, 0), 0) AS DIAMETRE_RAMAL,
    COALESCE(NULLIF(TRIM(raw."SIT_CLAU_PAS"), ''), '^^') AS SIT_CLAU_PAS,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_SIG_CTE_RAMAL"), '')), '0001-01-01'::DATE) AS DATA_SIG_CTE_RAMAL,
    COALESCE(NULLIF(TRIM(raw."TIP_SUBM_CTE_RAMAL"), ''), '^^') AS TIP_SUBM_CTE_RAMAL,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_JOC_CLAUS_CTE"), ''), 3, 0), 0) AS NOMB_JOC_CLAUS_CTE,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_PART_INST_RAM"), '')), '0001-01-01'::DATE) AS DATA_PART_INST_RAM,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_PART_INST_RAM"), ''), 5, 0), 0) AS NUM_PART_INST_RAM,
    COALESCE(NULLIF(TRIM(raw."QL_ARQUETA_ARMARI"), ''), '^^') AS QL_ARQUETA_ARMARI,
    COALESCE(NULLIF(TRIM(raw."ESTAT_ARQUETA_ARM"), ''), '^^') AS ESTAT_ARQUETA_ARM,
    COALESCE(NULLIF(TRIM(raw."ID_CIR_RECUP_AIGUA"), ''), '^^') AS ID_CIR_RECUP_AIGUA,
    NULLIF(TRIM(raw."NUM_SOL_LIC_AFEC"), '') AS NUM_SOL_LIC_AFEC,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_SOL_BAIXA_RAM"), '')), '0001-01-01'::DATE) AS DATA_SOL_BAIXA_RAM,
    COALESCE(NULLIF(TRIM(raw."DNI_NIF_CLIENT"), ''), '^^') AS DNI_NIF_CLIENT,
    COALESCE(NULLIF(TRIM(raw."NUM_MUN_SGAB"), ''), '^^') AS NUM_MUN_SGAB,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_CARRER"), ''), 6, 0), 0) AS NUM_CARRER,
    COALESCE(NULLIF(TRIM(raw."NUM_INI_FINCA"), ''), '^^') AS NUM_INI_FINCA,
    NULLIF(TRIM(raw."COMP_NUM_INI_FINCA"), '') AS COMP_NUM_INI_FINCA,
    COALESCE(NULLIF(TRIM(raw."NUM_FIN_FINCA"), ''), '^^') AS NUM_FIN_FINCA,
    NULLIF(TRIM(raw."COMP_NUM_FIN_FINCA"), '') AS COMP_NUM_FIN_FINCA,
    COALESCE(NULLIF(TRIM(raw."SIT_FINCA_ESPEC"), ''), '^^') AS SIT_FINCA_ESPEC,
    COALESCE(NULLIF(TRIM(raw."ORD_FINCA_ESPEC"), ''), '^^') AS ORD_FINCA_ESPEC,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_ORD_RAMAL"), ''), 2, 0), 0) AS NUM_ORD_RAMAL,
    NULLIF(TRIM(raw."POLISSA_RAMAL_AFEC"), '') AS POLISSA_RAMAL_AFEC,
    NULLIF(TRIM(raw."DNI_NIF_CLIENT_ORI"), '') AS DNI_NIF_CLIENT_ORI,
    COALESCE(NULLIF(TRIM(raw."OBS_PRESA_RAMAL"), ''), '^^') AS OBS_PRESA_RAMAL,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."RAMAL_CO"), ''), 7, 0) AS RAMAL_CO,
    COALESCE(NULLIF(TRIM(raw."QL_TIPUS_DADES_C"), ''), '^^') AS QL_TIPUS_DADES_C,
    COALESCE(NULLIF(TRIM(raw."QL_ANOT"), ''), '^^') AS QL_ANOT,
    NULLIF(TRIM(raw."SECCIO_CENSAL"), '') AS SECCIO_CENSAL,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_TZ, '{{ run_started_at.isoformat() }}'::TIMESTAMP_TZ) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP()) AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_RAMAL' AS TABLA_ORIGEN
from raw
