{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key=['POLISSA_SUBM'],
    schema='l4_fact',
    tags=['l4_fact', 'l4', 'bronze']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_submin_servei') }}
)

select
    COALESCE(NULLIF(TRIM(raw."POLISSA_SUBM"), ''), '^^') AS POLISSA_SUBM,
    COALESCE(NULLIF(TRIM(raw."DVER_POLISSA_SUBM"), ''), '^^') AS DVER_POLISSA_SUBM,
    COALESCE(NULLIF(TRIM(raw."TIP_SUBM_SERV"), ''), '^^') AS TIP_SUBM_SERV,
    COALESCE(NULLIF(TRIM(raw."SIT_SUBM_SERV"), ''), '^^') AS SIT_SUBM_SERV,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_CTE_SUBM_SERV"), '')), '0001-01-01'::DATE) AS DATA_CTE_SUBM_SERV,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_ALT_SUBM_SERV"), '')), '0001-01-01'::DATE) AS DATA_ALT_SUBM_SERV,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_RES_SUBM_SERV"), '')), '0001-01-01'::DATE) AS DATA_RES_SUBM_SERV,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."IMP_FIANSA"), ''), 9, 2), 0) AS IMP_FIANSA,
    COALESCE(NULLIF(TRIM(raw."SIT_FIANSA"), ''), '^^') AS SIT_FIANSA,
    COALESCE(TRY_TO_DATE(NULLIF(TRIM(raw."DATA_ULTIMA_FACT"), '')), '0001-01-01'::DATE) AS DATA_ULTIMA_FACT,
    COALESCE(NULLIF(TRIM(raw."QL_IDIOMA"), ''), '^^') AS QL_IDIOMA,
    COALESCE(NULLIF(TRIM(raw."ID_PAGA_IVA"), ''), '^^') AS ID_PAGA_IVA,
    COALESCE(NULLIF(TRIM(raw."US_AIGUA_SUBM"), ''), '^^') AS US_AIGUA_SUBM,
    COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_HABIT_SUBM"), ''), 3, 0), 0) AS NOMB_HABIT_SUBM,
    COALESCE(NULLIF(TRIM(raw."TIP_HABIT_SUBM"), ''), '^^') AS TIP_HABIT_SUBM,
    NULLIF(TRIM(raw."TIP_TAXA_TRR"), '') AS TIP_TAXA_TRR,
    COALESCE(NULLIF(TRIM(raw."POLISSA_RAMAL"), ''), '^^') AS POLISSA_RAMAL,
    COALESCE(NULLIF(TRIM(raw."PIS_PORTA_DESTI"), ''), '^^') AS PIS_PORTA_DESTI,
    COALESCE(NULLIF(TRIM(raw."DNI_NIF_CLIENT"), ''), '^^') AS DNI_NIF_CLIENT,
    COALESCE(NULLIF(TRIM(raw."NUM_ENTITAT_COBRA"), ''), '^^') AS NUM_ENTITAT_COBRA,
    COALESCE(NULLIF(TRIM(raw."NUM_AGENCIA_APART"), ''), '^^') AS NUM_AGENCIA_APART,
    COALESCE(NULLIF(TRIM(raw."NUM_COMPTE_DEPEND"), ''), '^^') AS NUM_COMPTE_DEPEND,
    COALESCE(NULLIF(TRIM(raw."NOM_TITULAR_COMPTE"), ''), '^^') AS NOM_TITULAR_COMPTE,
    NULLIF(TRIM(raw."ID_QUOTA_SOCIAL"), '') AS ID_QUOTA_SOCIAL,
    NULLIF(TRIM(raw."ID_TARIFA_SOCIAL"), '') AS ID_TARIFA_SOCIAL,
    NULLIF(TRIM(raw."IND_SERVEI_SOCIAL"), '') AS IND_SERVEI_SOCIAL,
    NULLIF(TRIM(raw."IND_POB_ENERG"), '') AS IND_POB_ENERG,
    NULLIF(TRIM(raw."NOM_COMERCIAL"), '') AS NOM_COMERCIAL,
    NULLIF(TRIM(raw."TIP_FACT_ENV"), '') AS TIP_FACT_ENV,
    NULLIF(TRIM(raw."CODI_PAIS"), '') AS CODI_PAIS,
    NULLIF(TRIM(raw."NUM_COMPTE_IBAN"), '') AS NUM_COMPTE_IBAN,
    NULLIF(TRIM(raw."IND_OKUPA"), '') AS IND_OKUPA,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_TZ, '{{ run_started_at.isoformat() }}'::TIMESTAMP_TZ) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP()) AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_SUBMIN_SERVEI' AS TABLA_ORIGEN
from raw
