{{ config(
    materialized='table',
    schema='l4_fact',
    tags=['l4_fact']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_fact_concepte') }}
)

select
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_PARTICIO"), ''), 2, 0) AS NUM_PARTICIO,
    NULLIF(TRIM(raw."ID_EMPRESA"), '') AS ID_EMPRESA,
    NULLIF(TRIM(raw."ANY_FACTURA"), '') AS ANY_FACTURA,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_FACTURA"), ''), 7, 0) AS NUM_FACTURA,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_LINEA"), ''), 3, 0) AS NUM_LINEA,
    NULLIF(TRIM(raw."NUM_CONCEPTE"), '') AS NUM_CONCEPTE,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."BASE_CONCEPTE"), ''), 11, 2) AS BASE_CONCEPTE,
    NULLIF(TRIM(raw."TIP_TAXA_CONCEP"), '') AS TIP_TAXA_CONCEP,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."PREU_CONCEPTE"), ''), 11, 4) AS PREU_CONCEPTE,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."IMP_CONCEPTE"), ''), 11, 2) AS IMP_CONCEPTE,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."IVA_APLICAT_CONC"), ''), 5, 2) AS IVA_APLICAT_CONC,
    NULLIF(TRIM(raw."OBSER_CONCEPTE"), '') AS OBSER_CONCEPTE,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_NTZ, raw.FECHA_EXTRACCION) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_FACT_CONCEPTE' AS TABLA_ORIGEN
from raw
