{{ config(
    materialized='table',
    schema='l4_fact',
    tags=['l4_fact']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_municipi_sgab') }}
)

select
    NULLIF(TRIM(raw."NUM_MUN_SGAB"), '') AS NUM_MUN_SGAB,
    NULLIF(TRIM(raw."NOM_MUN_SGAB"), '') AS NOM_MUN_SGAB,
    NULLIF(TRIM(raw."QL_CRITERI_FACT"), '') AS QL_CRITERI_FACT,
    NULLIF(TRIM(raw."ID_MUN_CP_UNIC"), '') AS ID_MUN_CP_UNIC,
    NULLIF(TRIM(raw."CP_PROVINCIA"), '') AS CP_PROVINCIA,
    NULLIF(TRIM(raw."UNITAT_REPARTIMENT"), '') AS UNITAT_REPARTIMENT,
    NULLIF(TRIM(raw."NUM_DTE_POST"), '') AS NUM_DTE_POST,
    NULLIF(TRIM(raw."NUM_DEL_SGAB"), '') AS NUM_DEL_SGAB,
    NULLIF(TRIM(raw."NUM_AGENCIA_SGAB"), '') AS NUM_AGENCIA_SGAB,
    NULLIF(TRIM(raw."ID_AREA_LECT"), '') AS ID_AREA_LECT,
    NULLIF(TRIM(raw."ID_EMPRESA"), '') AS ID_EMPRESA,
    NULLIF(TRIM(raw."DELEGA_CO"), '') AS DELEGA_CO,
    NULLIF(TRIM(raw."QL_GEST_DTE"), '') AS QL_GEST_DTE,
    NULLIF(TRIM(raw."ID_MUNI_ENT_MET"), '') AS ID_MUNI_ENT_MET,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_DIES_ANS"), ''), 3, 0) AS NOMB_DIES_ANS,
    NULLIF(TRIM(raw."MUNI_GENERALITAT"), '') AS MUNI_GENERALITAT,
    NULLIF(TRIM(raw."CODI_PROV"), '') AS CODI_PROV,
    NULLIF(TRIM(raw."CODI_MUNI"), '') AS CODI_MUNI,
    NULLIF(TRIM(raw."QL_TIPUS_VENDA"), '') AS QL_TIPUS_VENDA,
    NULLIF(TRIM(raw."CODI_MUNICIPI"), '') AS CODI_MUNICIPI,
    CAST(NULL AS NUMBER(3,0)) AS NOMB_DIES_INDEMN,
    CAST(NULL AS NUMBER(2,0)) AS NOMB_DIES_SENSE_AUT,
    CAST(NULL AS VARCHAR(1)) AS ADHERIT_L24,
    CAST(NULL AS VARCHAR(1)) AS CARTA_CIRER,
    CAST(NULL AS NUMBER(5,0)) AS NUM_CAIPS,
    CAST(NULL AS NUMBER(5,0)) AS NUM_DIAS_ENV_CAIPS,
    CAST(NULL AS VARCHAR(1)) AS CARTA_CIRER_2,
    CAST(NULL AS NUMBER(5,0)) AS NUM_DIAS_CIRER_2,
    CAST(NULL AS NUMBER(5,0)) AS NUM_DIAS_GENERA_CORTE,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_NTZ, raw.FECHA_EXTRACCION) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_MUNICIPI_SGAB' AS TABLA_ORIGEN
from raw
