{{ config(
    materialized='table',
    schema='l4_fact',
    tags=['l4_fact']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_padro_tamgrem') }}
)

select
    NULLIF(TRIM(raw."POLISSA_SUBM"), '') AS POLISSA_SUBM,
    TRY_TO_TIMESTAMP_NTZ(NULLIF(TRIM(raw."TS_PADRO_TAMGREM"), '')) AS TS_PADRO_TAMGREM,
    NULLIF(TRIM(raw."TIP_TAXA_TAMGREM"), '') AS TIP_TAXA_TAMGREM,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_HABIT_SUBM"), ''), 3, 0) AS NOMB_HABIT_SUBM,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."CONSUM_MES_BASE"), ''), 7, 0) AS CONSUM_MES_BASE,
    NULLIF(TRIM(raw."TIP_QUOTA_TAMGREM"), '') AS TIP_QUOTA_TAMGREM,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."CONSUM_MIG_DIA"), ''), 9, 4) AS CONSUM_MIG_DIA,
    NULLIF(TRIM(raw."NUMERO_EMPLEAT"), '') AS NUMERO_EMPLEAT,
    NULLIF(TRIM(raw."SECCIO"), '') AS SECCIO,
    NULLIF(TRIM(raw."EPIGRAF_IAE"), '') AS EPIGRAF_IAE,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."PERC_BONIF_TAMGREM"), ''), 5, 2) AS PERC_BONIF_TAMGREM,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."IMP_CUOTA"), ''), 11, 2) AS IMP_CUOTA,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."SUPERFICIE_REAL"), ''), 7, 0) AS SUPERFICIE_REAL,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."SUPERFICIE_POND"), ''), 9, 2) AS SUPERFICIE_POND,
    NULLIF(TRIM(raw."NIV_GEN_RES"), '') AS NIV_GEN_RES,
    NULLIF(TRIM(raw."COD_GEN_RES"), '') AS COD_GEN_RES,
    NULLIF(TRIM(raw."ORIGEN"), '') AS ORIGEN,
    NULLIF(TRIM(raw."ID_BONIF_DECGER"), '') AS ID_BONIF_DECGER,
    NULLIF(TRIM(raw."ID_LIMIT"), '') AS ID_LIMIT,
    NULLIF(TRIM(raw."SUBTIP_TAXA_TAMGREM"), '') AS SUBTIP_TAXA_TAMGREM,
    NULLIF(TRIM(raw."OBSERVACIONS"), '') AS OBSERVACIONS,
    TRY_TO_TIMESTAMP_NTZ(NULLIF(TRIM(raw."TS_ALTA"), '')) AS TS_ALTA,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_NTZ, raw.FECHA_EXTRACCION) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_PADRO_TAMGREM' AS TABLA_ORIGEN
from raw
