{{ config(
    materialized='table',
    schema='l4_fact',
    tags=['l4_fact']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_ramal') }}
)

select
    NULLIF(TRIM(raw."POLISSA_RAMAL"), '') AS POLISSA_RAMAL,
    NULLIF(TRIM(raw."DVER_POLISSA_RAMAL"), '') AS DVER_POLISSA_RAMAL,
    NULLIF(TRIM(raw."SIT_RAMAL"), '') AS SIT_RAMAL,
    NULLIF(TRIM(raw."TIP_OPER_RAMAL"), '') AS TIP_OPER_RAMAL,
    NULLIF(TRIM(raw."US_RAMAL"), '') AS US_RAMAL,
    NULLIF(TRIM(raw."MATERIAL_RAMAL"), '') AS MATERIAL_RAMAL,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_INST_RAMAL"), '')) AS DATA_INST_RAMAL,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."DIAMETRE_RAMAL"), ''), 3, 0) AS DIAMETRE_RAMAL,
    NULLIF(TRIM(raw."SIT_CLAU_PAS"), '') AS SIT_CLAU_PAS,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_SIG_CTE_RAMAL"), '')) AS DATA_SIG_CTE_RAMAL,
    NULLIF(TRIM(raw."TIP_SUBM_CTE_RAMAL"), '') AS TIP_SUBM_CTE_RAMAL,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_JOC_CLAUS_CTE"), ''), 3, 0) AS NOMB_JOC_CLAUS_CTE,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_PART_INST_RAM"), '')) AS DATA_PART_INST_RAM,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_PART_INST_RAM"), ''), 5, 0) AS NUM_PART_INST_RAM,
    NULLIF(TRIM(raw."QL_ARQUETA_ARMARI"), '') AS QL_ARQUETA_ARMARI,
    NULLIF(TRIM(raw."ESTAT_ARQUETA_ARM"), '') AS ESTAT_ARQUETA_ARM,
    NULLIF(TRIM(raw."ID_CIR_RECUP_AIGUA"), '') AS ID_CIR_RECUP_AIGUA,
    NULLIF(TRIM(raw."NUM_SOL_LIC_AFEC"), '') AS NUM_SOL_LIC_AFEC,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_SOL_BAIXA_RAM"), '')) AS DATA_SOL_BAIXA_RAM,
    NULLIF(TRIM(raw."DNI_NIF_CLIENT"), '') AS DNI_NIF_CLIENT,
    NULLIF(TRIM(raw."NUM_MUN_SGAB"), '') AS NUM_MUN_SGAB,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_CARRER"), ''), 6, 0) AS NUM_CARRER,
    NULLIF(TRIM(raw."NUM_INI_FINCA"), '') AS NUM_INI_FINCA,
    NULLIF(TRIM(raw."COMP_NUM_INI_FINCA"), '') AS COMP_NUM_INI_FINCA,
    NULLIF(TRIM(raw."NUM_FIN_FINCA"), '') AS NUM_FIN_FINCA,
    NULLIF(TRIM(raw."COMP_NUM_FIN_FINCA"), '') AS COMP_NUM_FIN_FINCA,
    NULLIF(TRIM(raw."SIT_FINCA_ESPEC"), '') AS SIT_FINCA_ESPEC,
    NULLIF(TRIM(raw."ORD_FINCA_ESPEC"), '') AS ORD_FINCA_ESPEC,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_ORD_RAMAL"), ''), 2, 0) AS NUM_ORD_RAMAL,
    NULLIF(TRIM(raw."POLISSA_RAMAL_AFEC"), '') AS POLISSA_RAMAL_AFEC,
    NULLIF(TRIM(raw."DNI_NIF_CLIENT_ORI"), '') AS DNI_NIF_CLIENT_ORI,
    NULLIF(TRIM(raw."OBS_PRESA_RAMAL"), '') AS OBS_PRESA_RAMAL,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."RAMAL_CO"), ''), 7, 0) AS RAMAL_CO,
    NULLIF(TRIM(raw."QL_TIPUS_DADES_C"), '') AS QL_TIPUS_DADES_C,
    NULLIF(TRIM(raw."QL_ANOT"), '') AS QL_ANOT,
    NULLIF(TRIM(raw."SECCIO_CENSAL"), '') AS SECCIO_CENSAL,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_NTZ, raw.FECHA_EXTRACCION) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_RAMAL' AS TABLA_ORIGEN
from raw
