{{ config(
    materialized='table',
    schema='l4_fact',
    tags=['l4_fact']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_servei_eq_ci') }}
)

select
    NULLIF(TRIM(raw."POLISSA_SUBM"), '') AS POLISSA_SUBM,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQUES_25"), ''), 3, 0) AS NOMB_BOQUES_25,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQUES_45"), ''), 3, 0) AS NOMB_BOQUES_45,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQUES_70"), ''), 3, 0) AS NOMB_BOQUES_70,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQUES_100"), ''), 3, 0) AS NOMB_BOQUES_100,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_SPRINCKLERS"), ''), 5, 0) AS NOMB_SPRINCKLERS,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NUM_PRECINTE_BOCA"), ''), 3, 0) AS NUM_PRECINTE_BOCA,
    NULLIF(TRIM(raw."ID_GRUP_ELEV_EQ_CI"), '') AS ID_GRUP_ELEV_EQ_CI,
    NULLIF(TRIM(raw."ID_VALVULA_MOTOR"), '') AS ID_VALVULA_MOTOR,
    NULLIF(TRIM(raw."TIP_PETIC_RES"), '') AS TIP_PETIC_RES,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_NTZ, raw.FECHA_EXTRACCION) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_SERVEI_EQ_CI' AS TABLA_ORIGEN
from raw
