{{ config(
    materialized='table',
    schema='l4_fact',
    tags=['l4_fact']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_submin_servei') }}
)

select
    NULLIF(TRIM(raw."POLISSA_SUBM"), '') AS POLISSA_SUBM,
    NULLIF(TRIM(raw."DVER_POLISSA_SUBM"), '') AS DVER_POLISSA_SUBM,
    NULLIF(TRIM(raw."TIP_SUBM_SERV"), '') AS TIP_SUBM_SERV,
    NULLIF(TRIM(raw."SIT_SUBM_SERV"), '') AS SIT_SUBM_SERV,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_CTE_SUBM_SERV"), '')) AS DATA_CTE_SUBM_SERV,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_ALT_SUBM_SERV"), '')) AS DATA_ALT_SUBM_SERV,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_RES_SUBM_SERV"), '')) AS DATA_RES_SUBM_SERV,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."IMP_FIANSA"), ''), 9, 2) AS IMP_FIANSA,
    NULLIF(TRIM(raw."SIT_FIANSA"), '') AS SIT_FIANSA,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_ULTIMA_FACT"), '')) AS DATA_ULTIMA_FACT,
    NULLIF(TRIM(raw."QL_IDIOMA"), '') AS QL_IDIOMA,
    NULLIF(TRIM(raw."ID_PAGA_IVA"), '') AS ID_PAGA_IVA,
    NULLIF(TRIM(raw."US_AIGUA_SUBM"), '') AS US_AIGUA_SUBM,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_HABIT_SUBM"), ''), 3, 0) AS NOMB_HABIT_SUBM,
    NULLIF(TRIM(raw."TIP_HABIT_SUBM"), '') AS TIP_HABIT_SUBM,
    NULLIF(TRIM(raw."TIP_TAXA_TRR"), '') AS TIP_TAXA_TRR,
    NULLIF(TRIM(raw."POLISSA_RAMAL"), '') AS POLISSA_RAMAL,
    NULLIF(TRIM(raw."PIS_PORTA_DESTI"), '') AS PIS_PORTA_DESTI,
    NULLIF(TRIM(raw."DNI_NIF_CLIENT"), '') AS DNI_NIF_CLIENT,
    NULLIF(TRIM(raw."NUM_ENTITAT_COBRA"), '') AS NUM_ENTITAT_COBRA,
    NULLIF(TRIM(raw."NUM_AGENCIA_APART"), '') AS NUM_AGENCIA_APART,
    NULLIF(TRIM(raw."NUM_COMPTE_DEPEND"), '') AS NUM_COMPTE_DEPEND,
    NULLIF(TRIM(raw."NOM_TITULAR_COMPTE"), '') AS NOM_TITULAR_COMPTE,
    NULLIF(TRIM(raw."ID_QUOTA_SOCIAL"), '') AS ID_QUOTA_SOCIAL,
    NULLIF(TRIM(raw."ID_TARIFA_SOCIAL"), '') AS ID_TARIFA_SOCIAL,
    NULLIF(TRIM(raw."IND_SERVEI_SOCIAL"), '') AS IND_SERVEI_SOCIAL,
    NULLIF(TRIM(raw."IND_POB_ENERG"), '') AS IND_POB_ENERG,
    NULLIF(TRIM(raw."NOM_COMERCIAL"), '') AS NOM_COMERCIAL,
    NULLIF(TRIM(raw."TIP_FACT_ENV"), '') AS TIP_FACT_ENV,
    NULLIF(TRIM(raw."CODI_PAIS"), '') AS CODI_PAIS,
    NULLIF(TRIM(raw."NUM_COMPTE_IBAN"), '') AS NUM_COMPTE_IBAN,
    NULLIF(TRIM(raw."IND_OKUPA"), '') AS IND_OKUPA,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_NTZ, raw.FECHA_EXTRACCION) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_SUBMIN_SERVEI' AS TABLA_ORIGEN
from raw
