{{ config(
    materialized='table',
    schema='l4_fact',
    tags=['l4_fact']
) }}

with raw as (
    select *
    from {{ source('raw_sicab', 'raw_servei_facturar') }}
)

select
    NULLIF(TRIM(raw."POLISSA_SUBM"), '') AS POLISSA_SUBM,
    TRY_TO_DATE(NULLIF(TRIM(raw."DATA_FIN_FACT"), '')) AS DATA_FIN_FACT,
    NULLIF(TRIM(raw."CALCUL_CONSUM_SERV"), '') AS CALCUL_CONSUM_SERV,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."DIES_CONSUM_SERV"), ''), 5, 0) AS DIES_CONSUM_SERV,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQ_25_SERV"), ''), 3, 0) AS NOMB_BOQ_25_SERV,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQ_45_SERV"), ''), 3, 0) AS NOMB_BOQ_45_SERV,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQ_70_SERV"), ''), 3, 0) AS NOMB_BOQ_70_SERV,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_BOQ_100_SERV"), ''), 3, 0) AS NOMB_BOQ_100_SERV,
    TRY_TO_DECIMAL(NULLIF(TRIM(raw."NOMB_SPRINCK_SERV"), ''), 5, 0) AS NOMB_SPRINCK_SERV,
    NULLIF(TRIM(raw."ID_BUTLLETA"), '') AS ID_BUTLLETA,
    NULLIF(TRIM(raw."ID_LOT_LECT"), '') AS ID_LOT_LECT,
    NULLIF(TRIM(raw."ANY_CALENDARI"), '') AS ANY_CALENDARI,
    NULLIF(TRIM(raw."MES_CALENDARI"), '') AS MES_CALENDARI,
    DATEDIFF('millisecond', '1970-01-01'::TIMESTAMP_NTZ, raw.FECHA_EXTRACCION) AS ID_CARGA,
    raw.FECHA_EXTRACCION AS FECHA_EXTRACCION,
    CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_CARGA,
    raw.SISTEMA_ORIGEN AS SISTEMA_ORIGEN,
    'RAW_SERVEI_FACTURAR' AS TABLA_ORIGEN
from raw
