USE DATABASE DES_AGUA_CLARA;
USE SCHEMA RAW_SICAB;

COPY INTO RAW_CARRER ("NUM_MUN_SGAB", "NUM_CARRER", "CLASSE_CARRER", "NOM_ABREUJ_CARRER", "TIP_DENOMIN_CARRER", "NOM_COMPLET_CARRER", "ID_CARRER_SAP", "QL_CARRER", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "NUM_MUN_SGAB", $2 AS "NUM_CARRER", $3 AS "CLASSE_CARRER", $4 AS "NOM_ABREUJ_CARRER", $5 AS "TIP_DENOMIN_CARRER", $6 AS "NOM_COMPLET_CARRER", $7 AS "ID_CARRER_SAP", $8 AS "QL_CARRER",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/carrer.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_CODIFICATIONS ("TIP_CODI", "CLAU_CODI", "DESC_CODI", "DESC_BREU", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "TIP_CODI", $2 AS "CLAU_CODI", $3 AS "DESC_CODI", $4 AS "DESC_BREU",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/codifications.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_CONVENI_FRAU ("POLISSA_SUBM", "NUM_MUN_CONV_FRAU", "ADRE_CONV_FRAU", "COD_POST_CONV_FRAU", "DEL_CREACIO_CONV_F", "DATA_CREA_C_FRA", "POLISSA_RAMAL", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "NUM_MUN_CONV_FRAU", $3 AS "ADRE_CONV_FRAU", $4 AS "COD_POST_CONV_FRAU", $5 AS "DEL_CREACIO_CONV_F", $6 AS "DATA_CREA_C_FRA", $7 AS "POLISSA_RAMAL",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/conveni_frau.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_DTE_MUNICIPAL ("NUM_MUN_SGAB", "NUM_DTE_MUNI", "NOM_DTE_MUNI", "NUM_DEL_SGAB", "NUM_AGENCIA_SGAB", "CODI_AREA_SD", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "NUM_MUN_SGAB", $2 AS "NUM_DTE_MUNI", $3 AS "NOM_DTE_MUNI", $4 AS "NUM_DEL_SGAB", $5 AS "NUM_AGENCIA_SGAB", $6 AS "CODI_AREA_SD",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/dte_municipal.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_EPIGRAF_IAE ("SECCIO", "EPIGRAF_IAE", "DESCR_IAE", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "SECCIO", $2 AS "EPIGRAF_IAE", $3 AS "DESCR_IAE",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/epigraf_iae.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_FACT_AIGUA ("NUM_PARTICIO", "ID_EMPRESA", "ANY_FACTURA", "NUM_FACTURA", "DIAM_COMP_FACT", "DIAM_COMP_SEC_FACT", "MARCA_COMP_FACT", "NUM_COMP_FACT", "PROPIETAT_COMP_FA", "CABAL_NOMINAL_CTE", "IMP_QTA_SERV", "PREU_M3_BLOC1_FACT", "IMP_BLOC1", "PREU_M3_BLOC2_FACT", "IMP_BLOC2", "PREU_M3_BLOC3_FACT", "IMP_BLOC3", "TIP_CT_XBASICA_FAC", "BASE_CT_XBASICA", "PREU_CT_XBASICA_FA", "IMP_CT_XBASICA", "TIP_TCG_SUBM_FACT", "BASE_TCG_SUBM", "PREU_TCG_SUBM_FACT", "IMP_TCG_SUBM", "TIP_CLAVAG_FACT", "BASE_CLAVAG", "PREU_CLAVAG_FACT", "IMP_CLAVAG", "TIP_SANEJA_FACT", "BASE_SANEJA", "PREU_SANEJA_FACT", "IMP_SANEJA", "BASE_IVA_SANEJA", "IMP_IVA_SANEJA", "BASE_IVA", "PERCENT_IVA_FACT", "IMP_IVA", "TIP_ERSU_FACT", "BASE_ERSU", "PREU_ERSU_FACT", "IMP_ERSU", "TIP_CIH_FACT", "BASE_CIH_BLOC1", "PREU_CIH_BLOC1_FA", "IMP_CIH_BLOC1", "BASE_CIH_BLOC2", "PREU_CIH_BLOC2_FA", "IMP_CIH_BLOC2", "BASE_CIH_BLOC3", "PREU_CIH_BLOC3_FA", "IMP_CIH_BLOC3", "CABAL_CTE", "COEF_CIH_IND_FAC", "QL_1999_2000", "NOMBRE_PERSONES", "LIMIT_TRAM1_FACT", "LIMIT_TRAM2_FACT", "LIMIT_CAI1_FACT", "LIMIT_CLAV1_FACT", "LIMIT_CAI2_FACT", "NOMBRE_PER_CAI", "NOMBRE_PER_TMTR", "NUM_COMPT_T_FACT", "PREU_M3_BLOC4_FACT", "IMP_BLOC4", "PREU_M3_BLOC5_FACT", "IMP_BLOC5", "LIMIT_TRAM3_FACT", "LIMIT_TRAM4_FACT", "LIMIT_CAI3_FACT", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "NUM_PARTICIO", $2 AS "ID_EMPRESA", $3 AS "ANY_FACTURA", $4 AS "NUM_FACTURA", $5 AS "DIAM_COMP_FACT", $6 AS "DIAM_COMP_SEC_FACT", $7 AS "MARCA_COMP_FACT", $8 AS "NUM_COMP_FACT", $9 AS "PROPIETAT_COMP_FA", $10 AS "CABAL_NOMINAL_CTE", $11 AS "IMP_QTA_SERV", $12 AS "PREU_M3_BLOC1_FACT", $13 AS "IMP_BLOC1", $14 AS "PREU_M3_BLOC2_FACT", $15 AS "IMP_BLOC2", $16 AS "PREU_M3_BLOC3_FACT", $17 AS "IMP_BLOC3", $18 AS "TIP_CT_XBASICA_FAC", $19 AS "BASE_CT_XBASICA", $20 AS "PREU_CT_XBASICA_FA", $21 AS "IMP_CT_XBASICA", $22 AS "TIP_TCG_SUBM_FACT", $23 AS "BASE_TCG_SUBM", $24 AS "PREU_TCG_SUBM_FACT", $25 AS "IMP_TCG_SUBM", $26 AS "TIP_CLAVAG_FACT", $27 AS "BASE_CLAVAG", $28 AS "PREU_CLAVAG_FACT", $29 AS "IMP_CLAVAG", $30 AS "TIP_SANEJA_FACT", $31 AS "BASE_SANEJA", $32 AS "PREU_SANEJA_FACT", $33 AS "IMP_SANEJA", $34 AS "BASE_IVA_SANEJA", $35 AS "IMP_IVA_SANEJA", $36 AS "BASE_IVA", $37 AS "PERCENT_IVA_FACT", $38 AS "IMP_IVA", $39 AS "TIP_ERSU_FACT", $40 AS "BASE_ERSU", $41 AS "PREU_ERSU_FACT", $42 AS "IMP_ERSU", $43 AS "TIP_CIH_FACT", $44 AS "BASE_CIH_BLOC1", $45 AS "PREU_CIH_BLOC1_FA", $46 AS "IMP_CIH_BLOC1", $47 AS "BASE_CIH_BLOC2", $48 AS "PREU_CIH_BLOC2_FA", $49 AS "IMP_CIH_BLOC2", $50 AS "BASE_CIH_BLOC3", $51 AS "PREU_CIH_BLOC3_FA", $52 AS "IMP_CIH_BLOC3", $53 AS "CABAL_CTE", $54 AS "COEF_CIH_IND_FAC", $55 AS "QL_1999_2000", $56 AS "NOMBRE_PERSONES", $57 AS "LIMIT_TRAM1_FACT", $58 AS "LIMIT_TRAM2_FACT", $59 AS "LIMIT_CAI1_FACT", $60 AS "LIMIT_CLAV1_FACT", $61 AS "LIMIT_CAI2_FACT", $62 AS "NOMBRE_PER_CAI", $63 AS "NOMBRE_PER_TMTR", $64 AS "NUM_COMPT_T_FACT", $65 AS "PREU_M3_BLOC4_FACT", $66 AS "IMP_BLOC4", $67 AS "PREU_M3_BLOC5_FACT", $68 AS "IMP_BLOC5", $69 AS "LIMIT_TRAM3_FACT", $70 AS "LIMIT_TRAM4_FACT", $71 AS "LIMIT_CAI3_FACT",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/fact_aigua.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_FACT_CONCEPTE ("NUM_PARTICIO", "ID_EMPRESA", "ANY_FACTURA", "NUM_FACTURA", "NUM_LINEA", "NUM_CONCEPTE", "BASE_CONCEPTE", "TIP_TAXA_CONCEP", "PREU_CONCEPTE", "IMP_CONCEPTE", "IVA_APLICAT_CONC", "OBSER_CONCEPTE", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "NUM_PARTICIO", $2 AS "ID_EMPRESA", $3 AS "ANY_FACTURA", $4 AS "NUM_FACTURA", $5 AS "NUM_LINEA", $6 AS "NUM_CONCEPTE", $7 AS "BASE_CONCEPTE", $8 AS "TIP_TAXA_CONCEP", $9 AS "PREU_CONCEPTE", $10 AS "IMP_CONCEPTE", $11 AS "IVA_APLICAT_CONC", $12 AS "OBSER_CONCEPTE",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/fact_concepte.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_FACT_RESUM ("ID_EMPRESA", "ANY_FACTURA", "NUM_FACTURA", "QL_EMPLEAT_SGAB", "FREQ_FACT", "M3_BLOC1", "M3_BLOC2", "M3_BLOC3", "M3_BLOC4", "M3_BLOC5", "IMP_TOTAL_FACT", "IMP_AIGUA_IVA", "ID_RECUPERACIO", "ID_REGULARITZACIO", "DATA_CARREC_RECAP", "IDEN_LOT_LECT_FACT", "NUM_PARTICIO", "POLISSA_SUBM", "DATA_FIN_FACT", "ID_LOT_FACT", "ANY_CALENDARI", "MES_CALENDARI", "ID_CONCEPTES", "ID_DECLARADA", "DNI_NIF_CLIENT", "QL_GESTIO_FACT", "QL_TIP_COBRA", "NUM_ENTITAT_COBR", "NUM_AGENCIA_APAR", "NUM_COMPTE_DEPEN", "DVER_COMPTE_BANC", "TIP_FACTURA", "DATA_EMISS_FACT", "DATA_INI_FACT", "QL_RESUM_COMPTABLE", "TIP_QTA_SERV_FACT", "ID_CALCUL_DIARI", "US_AIGUA_SUBM_FACT", "TIP_HABIT_SUBM_FA", "NOMB_HABIT_FACT", "SIT_SUBM_SERV_FACT", "QL_IDIOMA_FACT", "PUBLI_OFI_TARI_FA", "ID_CARREC_SOCIETAT", "QL_MONEDA", "TIP_SUBM_SERV", "NOM_CLIENT", "NUM_INDEX", "APROVADA_FACT", "QL_TIP_COBRA_INI", "QL_ENVIO_FACT", "TIP_DOMESTIC", "QL_DCL_CAI", "TIP_FACT_ENV", "EMISSORA", "NUM_COMPTE_IBAN", "TIP_FACT_SII", "TIPUS_FACTURA", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "ID_EMPRESA", $2 AS "ANY_FACTURA", $3 AS "NUM_FACTURA", $4 AS "QL_EMPLEAT_SGAB", $5 AS "FREQ_FACT", $6 AS "M3_BLOC1", $7 AS "M3_BLOC2", $8 AS "M3_BLOC3", $9 AS "M3_BLOC4", $10 AS "M3_BLOC5", $11 AS "IMP_TOTAL_FACT", $12 AS "IMP_AIGUA_IVA", $13 AS "ID_RECUPERACIO", $14 AS "ID_REGULARITZACIO", $15 AS "DATA_CARREC_RECAP", $16 AS "IDEN_LOT_LECT_FACT", $17 AS "NUM_PARTICIO", $18 AS "POLISSA_SUBM", $19 AS "DATA_FIN_FACT", $20 AS "ID_LOT_FACT", $21 AS "ANY_CALENDARI", $22 AS "MES_CALENDARI", $23 AS "ID_CONCEPTES", $24 AS "ID_DECLARADA", $25 AS "DNI_NIF_CLIENT", $26 AS "QL_GESTIO_FACT", $27 AS "QL_TIP_COBRA", $28 AS "NUM_ENTITAT_COBR", $29 AS "NUM_AGENCIA_APAR", $30 AS "NUM_COMPTE_DEPEN", $31 AS "DVER_COMPTE_BANC", $32 AS "TIP_FACTURA", $33 AS "DATA_EMISS_FACT", $34 AS "DATA_INI_FACT", $35 AS "QL_RESUM_COMPTABLE", $36 AS "TIP_QTA_SERV_FACT", $37 AS "ID_CALCUL_DIARI", $38 AS "US_AIGUA_SUBM_FACT", $39 AS "TIP_HABIT_SUBM_FA", $40 AS "NOMB_HABIT_FACT", $41 AS "SIT_SUBM_SERV_FACT", $42 AS "QL_IDIOMA_FACT", $43 AS "PUBLI_OFI_TARI_FA", $44 AS "ID_CARREC_SOCIETAT", $45 AS "QL_MONEDA", $46 AS "TIP_SUBM_SERV", $47 AS "NOM_CLIENT", $48 AS "NUM_INDEX", $49 AS "APROVADA_FACT", $50 AS "QL_TIP_COBRA_INI", $51 AS "QL_ENVIO_FACT", $52 AS "TIP_DOMESTIC", $53 AS "QL_DCL_CAI", $54 AS "TIP_FACT_ENV", $55 AS "EMISSORA", $56 AS "NUM_COMPTE_IBAN", $57 AS "TIP_FACT_SII", $58 AS "TIPUS_FACTURA",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/fact_resum.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_FINCA ("NUM_MUN_SGAB", "NUM_CARRER", "NUM_INI_FINCA", "COMP_NUM_INI_FINCA", "NUM_FIN_FINCA", "COMP_NUM_FIN_FINCA", "SIT_FINCA_ESPEC", "ORD_FINCA_ESPEC", "NUM_TORN_LECT_MENS", "ORD_FINCA_TORN_MEN", "NUM_DTE_POST_FINCA", "ESTAT_FINCA", "ID_GRUP_ELEV_FINCA", "PRES_XARXA_FINCA", "CAT_FISCAL_FINCA", "ALTURA_FINCA", "ID_FINCA_RENDA_LIM", "NUM_EXP_RENDA_LIM", "NUM_ZONA_RECOR", "NUM_TRAVES", "CASA_RECOR_PERIOD", "NUM_NUS_XARXA", "ID_LOT_LECT", "OBS_ADRE_INCOMPLET", "PARTICULARIT_FINCA", "LOCAL_CLAUS_FINCA", "QL_COMPT_ELECTRON", "NUM_DTE_MUNI_FINCA", "QL_BATERIA_CABLE", "CODI_UBICACIO_SAP", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "NUM_MUN_SGAB", $2 AS "NUM_CARRER", $3 AS "NUM_INI_FINCA", $4 AS "COMP_NUM_INI_FINCA", $5 AS "NUM_FIN_FINCA", $6 AS "COMP_NUM_FIN_FINCA", $7 AS "SIT_FINCA_ESPEC", $8 AS "ORD_FINCA_ESPEC", $9 AS "NUM_TORN_LECT_MENS", $10 AS "ORD_FINCA_TORN_MEN", $11 AS "NUM_DTE_POST_FINCA", $12 AS "ESTAT_FINCA", $13 AS "ID_GRUP_ELEV_FINCA", $14 AS "PRES_XARXA_FINCA", $15 AS "CAT_FISCAL_FINCA", $16 AS "ALTURA_FINCA", $17 AS "ID_FINCA_RENDA_LIM", $18 AS "NUM_EXP_RENDA_LIM", $19 AS "NUM_ZONA_RECOR", $20 AS "NUM_TRAVES", $21 AS "CASA_RECOR_PERIOD", $22 AS "NUM_NUS_XARXA", $23 AS "ID_LOT_LECT", $24 AS "OBS_ADRE_INCOMPLET", $25 AS "PARTICULARIT_FINCA", $26 AS "LOCAL_CLAUS_FINCA", $27 AS "QL_COMPT_ELECTRON", $28 AS "NUM_DTE_MUNI_FINCA", $29 AS "QL_BATERIA_CABLE", $30 AS "CODI_UBICACIO_SAP",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/finca.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_HIST_SS_PE ("POLISSA_SUBM", "TS_MOM_IND", "TIP_COLECTIVO", "DATA_INI_IND", "DATA_FIN_IND", "OBSERVACIONS", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "TS_MOM_IND", $3 AS "TIP_COLECTIVO", $4 AS "DATA_INI_IND", $5 AS "DATA_FIN_IND", $6 AS "OBSERVACIONS",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/hist_ss_pe.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_MUNICIPI_SGAB ("NUM_MUN_SGAB", "NOM_MUN_SGAB", "QL_CRITERI_FACT", "ID_MUN_CP_UNIC", "CP_PROVINCIA", "UNITAT_REPARTIMENT", "NUM_DTE_POST", "NUM_DEL_SGAB", "NUM_AGENCIA_SGAB", "ID_AREA_LECT", "ID_EMPRESA", "DELEGA_CO", "QL_GEST_DTE", "ID_MUNI_ENT_MET", "NOMB_DIES_ANS", "MUNI_GENERALITAT", "CODI_PROV", "CODI_MUNI", "QL_TIPUS_VENDA", "CODI_MUNICIPI", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "NUM_MUN_SGAB", $2 AS "NOM_MUN_SGAB", $3 AS "QL_CRITERI_FACT", $4 AS "ID_MUN_CP_UNIC", $5 AS "CP_PROVINCIA", $6 AS "UNITAT_REPARTIMENT", $7 AS "NUM_DTE_POST", $8 AS "NUM_DEL_SGAB", $9 AS "NUM_AGENCIA_SGAB", $10 AS "ID_AREA_LECT", $11 AS "ID_EMPRESA", $12 AS "DELEGA_CO", $13 AS "QL_GEST_DTE", $14 AS "ID_MUNI_ENT_MET", $15 AS "NOMB_DIES_ANS", $16 AS "MUNI_GENERALITAT", $17 AS "CODI_PROV", $18 AS "CODI_MUNI", $19 AS "QL_TIPUS_VENDA", $20 AS "CODI_MUNICIPI",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/municipi_sgab.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_PADRO_TAMGREM ("POLISSA_SUBM", "TS_PADRO_TAMGREM", "TIP_TAXA_TAMGREM", "NOMB_HABIT_SUBM", "CONSUM_MES_BASE", "TIP_QUOTA_TAMGREM", "CONSUM_MIG_DIA", "NUMERO_EMPLEAT", "SECCIO", "EPIGRAF_IAE", "PERC_BONIF_TAMGREM", "IMP_CUOTA", "SUPERFICIE_REAL", "SUPERFICIE_POND", "NIV_GEN_RES", "COD_GEN_RES", "ORIGEN", "ID_BONIF_DECGER", "ID_LIMIT", "SUBTIP_TAXA_TAMGREM", "OBSERVACIONS", "TS_ALTA", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "TS_PADRO_TAMGREM", $3 AS "TIP_TAXA_TAMGREM", $4 AS "NOMB_HABIT_SUBM", $5 AS "CONSUM_MES_BASE", $6 AS "TIP_QUOTA_TAMGREM", $7 AS "CONSUM_MIG_DIA", $8 AS "NUMERO_EMPLEAT", $9 AS "SECCIO", $10 AS "EPIGRAF_IAE", $11 AS "PERC_BONIF_TAMGREM", $12 AS "IMP_CUOTA", $13 AS "SUPERFICIE_REAL", $14 AS "SUPERFICIE_POND", $15 AS "NIV_GEN_RES", $16 AS "COD_GEN_RES", $17 AS "ORIGEN", $18 AS "ID_BONIF_DECGER", $19 AS "ID_LIMIT", $20 AS "SUBTIP_TAXA_TAMGREM", $21 AS "OBSERVACIONS", $22 AS "TS_ALTA",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/padro_tamgrem.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_PADRO_TRR ("POLISSA_SUBM", "TS_PADRO_TRR", "TIP_TAXA_TRR", "NOMB_HABIT_SUBM", "CONSUM_MES_BASE", "TIP_QUOTA_TRR", "CONSUM_MIG_DIA", "NUMERO_EMPLEAT", "SECCIO", "EPIGRAF_IAE", "PERC_BONIF_TRR", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "TS_PADRO_TRR", $3 AS "TIP_TAXA_TRR", $4 AS "NOMB_HABIT_SUBM", $5 AS "CONSUM_MES_BASE", $6 AS "TIP_QUOTA_TRR", $7 AS "CONSUM_MIG_DIA", $8 AS "NUMERO_EMPLEAT", $9 AS "SECCIO", $10 AS "EPIGRAF_IAE", $11 AS "PERC_BONIF_TRR",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/padro_trr.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_RAMAL ("POLISSA_RAMAL", "DVER_POLISSA_RAMAL", "SIT_RAMAL", "TIP_OPER_RAMAL", "US_RAMAL", "MATERIAL_RAMAL", "DATA_INST_RAMAL", "DIAMETRE_RAMAL", "SIT_CLAU_PAS", "DATA_SIG_CTE_RAMAL", "TIP_SUBM_CTE_RAMAL", "NOMB_JOC_CLAUS_CTE", "DATA_PART_INST_RAM", "NUM_PART_INST_RAM", "QL_ARQUETA_ARMARI", "ESTAT_ARQUETA_ARM", "ID_CIR_RECUP_AIGUA", "NUM_SOL_LIC_AFEC", "DATA_SOL_BAIXA_RAM", "DNI_NIF_CLIENT", "NUM_MUN_SGAB", "NUM_CARRER", "NUM_INI_FINCA", "COMP_NUM_INI_FINCA", "NUM_FIN_FINCA", "COMP_NUM_FIN_FINCA", "SIT_FINCA_ESPEC", "ORD_FINCA_ESPEC", "NUM_ORD_RAMAL", "POLISSA_RAMAL_AFEC", "DNI_NIF_CLIENT_ORI", "OBS_PRESA_RAMAL", "RAMAL_CO", "QL_TIPUS_DADES_C", "QL_ANOT", "SECCIO_CENSAL", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_RAMAL", $2 AS "DVER_POLISSA_RAMAL", $3 AS "SIT_RAMAL", $4 AS "TIP_OPER_RAMAL", $5 AS "US_RAMAL", $6 AS "MATERIAL_RAMAL", $7 AS "DATA_INST_RAMAL", $8 AS "DIAMETRE_RAMAL", $9 AS "SIT_CLAU_PAS", $10 AS "DATA_SIG_CTE_RAMAL", $11 AS "TIP_SUBM_CTE_RAMAL", $12 AS "NOMB_JOC_CLAUS_CTE", $13 AS "DATA_PART_INST_RAM", $14 AS "NUM_PART_INST_RAM", $15 AS "QL_ARQUETA_ARMARI", $16 AS "ESTAT_ARQUETA_ARM", $17 AS "ID_CIR_RECUP_AIGUA", $18 AS "NUM_SOL_LIC_AFEC", $19 AS "DATA_SOL_BAIXA_RAM", $20 AS "DNI_NIF_CLIENT", $21 AS "NUM_MUN_SGAB", $22 AS "NUM_CARRER", $23 AS "NUM_INI_FINCA", $24 AS "COMP_NUM_INI_FINCA", $25 AS "NUM_FIN_FINCA", $26 AS "COMP_NUM_FIN_FINCA", $27 AS "SIT_FINCA_ESPEC", $28 AS "ORD_FINCA_ESPEC", $29 AS "NUM_ORD_RAMAL", $30 AS "POLISSA_RAMAL_AFEC", $31 AS "DNI_NIF_CLIENT_ORI", $32 AS "OBS_PRESA_RAMAL", $33 AS "RAMAL_CO", $34 AS "QL_TIPUS_DADES_C", $35 AS "QL_ANOT", $36 AS "SECCIO_CENSAL",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/ramal.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_SERVEI_EQ_CI ("POLISSA_SUBM", "NOMB_BOQUES_25", "NOMB_BOQUES_45", "NOMB_BOQUES_70", "NOMB_BOQUES_100", "NOMB_SPRINCKLERS", "NUM_PRECINTE_BOCA", "ID_GRUP_ELEV_EQ_CI", "ID_VALVULA_MOTOR", "TIP_PETIC_RES", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "NOMB_BOQUES_25", $3 AS "NOMB_BOQUES_45", $4 AS "NOMB_BOQUES_70", $5 AS "NOMB_BOQUES_100", $6 AS "NOMB_SPRINCKLERS", $7 AS "NUM_PRECINTE_BOCA", $8 AS "ID_GRUP_ELEV_EQ_CI", $9 AS "ID_VALVULA_MOTOR", $10 AS "TIP_PETIC_RES",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/servei_eq_ci.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_SERVEI_FACTURAR ("POLISSA_SUBM", "DATA_FIN_FACT", "CALCUL_CONSUM_SERV", "DIES_CONSUM_SERV", "NOMB_BOQ_25_SERV", "NOMB_BOQ_45_SERV", "NOMB_BOQ_70_SERV", "NOMB_BOQ_100_SERV", "NOMB_SPRINCK_SERV", "ID_BUTLLETA", "ID_LOT_LECT", "ANY_CALENDARI", "MES_CALENDARI", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "DATA_FIN_FACT", $3 AS "CALCUL_CONSUM_SERV", $4 AS "DIES_CONSUM_SERV", $5 AS "NOMB_BOQ_25_SERV", $6 AS "NOMB_BOQ_45_SERV", $7 AS "NOMB_BOQ_70_SERV", $8 AS "NOMB_BOQ_100_SERV", $9 AS "NOMB_SPRINCK_SERV", $10 AS "ID_BUTLLETA", $11 AS "ID_LOT_LECT", $12 AS "ANY_CALENDARI", $13 AS "MES_CALENDARI",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/servei_facturar.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_SITUACIO_FACT ("NUM_PARTICIO", "ID_EMPRESA", "ANY_FACTURA", "NUM_FACTURA", "MOM_SIT_FACT", "TIP_SIT_FACT", "CAUSA_SIT_FACT", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "NUM_PARTICIO", $2 AS "ID_EMPRESA", $3 AS "ANY_FACTURA", $4 AS "NUM_FACTURA", $5 AS "MOM_SIT_FACT", $6 AS "TIP_SIT_FACT", $7 AS "CAUSA_SIT_FACT",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/situacio_fact.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_SUBMIN_IAE ("POLISSA_SUBM", "SECCIO", "EPIGRAF_IAE", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "SECCIO", $3 AS "EPIGRAF_IAE",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/submin_iae.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

COPY INTO RAW_SUBMIN_SERVEI ("POLISSA_SUBM", "DVER_POLISSA_SUBM", "TIP_SUBM_SERV", "SIT_SUBM_SERV", "DATA_CTE_SUBM_SERV", "DATA_ALT_SUBM_SERV", "DATA_RES_SUBM_SERV", "IMP_FIANSA", "SIT_FIANSA", "DATA_ULTIMA_FACT", "QL_IDIOMA", "ID_PAGA_IVA", "US_AIGUA_SUBM", "NOMB_HABIT_SUBM", "TIP_HABIT_SUBM", "TIP_TAXA_TRR", "POLISSA_RAMAL", "PIS_PORTA_DESTI", "DNI_NIF_CLIENT", "NUM_ENTITAT_COBRA", "NUM_AGENCIA_APART", "NUM_COMPTE_DEPEND", "NOM_TITULAR_COMPTE", "ID_QUOTA_SOCIAL", "ID_TARIFA_SOCIAL", "IND_SERVEI_SOCIAL", "IND_POB_ENERG", "NOM_COMERCIAL", "TIP_FACT_ENV", "CODI_PAIS", "NUM_COMPTE_IBAN", "IND_OKUPA", FECHA_EXTRACCION, SISTEMA_ORIGEN)
FROM (
    SELECT
        $1 AS "POLISSA_SUBM", $2 AS "DVER_POLISSA_SUBM", $3 AS "TIP_SUBM_SERV", $4 AS "SIT_SUBM_SERV", $5 AS "DATA_CTE_SUBM_SERV", $6 AS "DATA_ALT_SUBM_SERV", $7 AS "DATA_RES_SUBM_SERV", $8 AS "IMP_FIANSA", $9 AS "SIT_FIANSA", $10 AS "DATA_ULTIMA_FACT", $11 AS "QL_IDIOMA", $12 AS "ID_PAGA_IVA", $13 AS "US_AIGUA_SUBM", $14 AS "NOMB_HABIT_SUBM", $15 AS "TIP_HABIT_SUBM", $16 AS "TIP_TAXA_TRR", $17 AS "POLISSA_RAMAL", $18 AS "PIS_PORTA_DESTI", $19 AS "DNI_NIF_CLIENT", $20 AS "NUM_ENTITAT_COBRA", $21 AS "NUM_AGENCIA_APART", $22 AS "NUM_COMPTE_DEPEND", $23 AS "NOM_TITULAR_COMPTE", $24 AS "ID_QUOTA_SOCIAL", $25 AS "ID_TARIFA_SOCIAL", $26 AS "IND_SERVEI_SOCIAL", $27 AS "IND_POB_ENERG", $28 AS "NOM_COMERCIAL", $29 AS "TIP_FACT_ENV", $30 AS "CODI_PAIS", $31 AS "NUM_COMPTE_IBAN", $32 AS "IND_OKUPA",
        CONVERT_TIMEZONE('Europe/Madrid', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS FECHA_EXTRACCION,
        'SICAB' AS SISTEMA_ORIGEN
    FROM @RAW_STAGE/submin_servei.csv
)
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ';' SKIP_HEADER = 1 NULL_IF = ('', 'NULL'));

