CREATE OR REPLACE TABLE L4_CODIFICACIONS (
 
TIP_CODI VARCHAR(3) NOT NULL,
CLAU_CODI VARCHAR(5) NOT NULL,
DESC_CODI VARCHAR(50) NOT NULL,
DESC_BREU VARCHAR(20) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_CODIFICACIONS
PRIMARY KEY (TIP_CODI, CLAU_CODI)
 
);

CREATE OR REPLACE TABLE L4_MUNICIPI_SGAB (
 
NUM_MUN_SGAB VARCHAR(2) NOT NULL,
NOM_MUN_SGAB VARCHAR(20) NOT NULL,
QL_CRITERI_FACT VARCHAR(1) NOT NULL,
ID_MUN_CP_UNIC VARCHAR(1) NOT NULL,
CP_PROVINCIA VARCHAR(2) NOT NULL,
UNITAT_REPARTIMENT VARCHAR(1) NOT NULL,
NUM_DTE_POST VARCHAR(2) NOT NULL,
NUM_DEL_SGAB VARCHAR(2) NOT NULL,
NUM_AGENCIA_SGAB VARCHAR(2) NOT NULL,
ID_AREA_LECT VARCHAR(1) NOT NULL,
ID_EMPRESA VARCHAR(2) NOT NULL,
DELEGA_CO VARCHAR(1),
QL_GEST_DTE VARCHAR(1) NOT NULL,
ID_MUNI_ENT_MET VARCHAR(1) NOT NULL,
NOMB_DIES_ANS NUMBER(3,0) NOT NULL,
MUNI_GENERALITAT VARCHAR(5),
CODI_PROV VARCHAR(2),
CODI_MUNI VARCHAR(4),
QL_TIPUS_VENDA VARCHAR(1) NOT NULL,
CODI_MUNICIPI VARCHAR(3),
 
NOMB_DIES_INDEMN NUMBER(3,0),
NOMB_DIES_SENSE_AUT NUMBER(2,0),
ADHERIT_L24 VARCHAR(1),
CARTA_CIRER VARCHAR(1),
NUM_CAIPS NUMBER(5,0),
NUM_DIAS_ENV_CAIPS NUMBER(5,0),
CARTA_CIRER_2 VARCHAR(1),
NUM_DIAS_CIRER_2 NUMBER(5,0),
NUM_DIAS_GENERA_CORTE NUMBER(5,0),
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_MUNICIPI_SGAB
PRIMARY KEY (NUM_MUN_SGAB)
 
);

CREATE OR REPLACE TABLE L4_DTE_MUNICIPAL (
 
NUM_MUN_SGAB VARCHAR(2) NOT NULL,
NUM_DTE_MUNI VARCHAR(2) NOT NULL,
NOM_DTE_MUNI VARCHAR(35) NOT NULL,
NUM_DEL_SGAB VARCHAR(2) NOT NULL,
NUM_AGENCIA_SGAB VARCHAR(2) NOT NULL,
CODI_AREA_SD VARCHAR(1) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_DTE_MUNICIPAL
PRIMARY KEY (NUM_MUN_SGAB, NUM_DTE_MUNI)
 
);

ALTER TABLE L4_DTE_MUNICIPAL
ADD CONSTRAINT FK_DTE_MUNICIPAL_MUNICIPI
FOREIGN KEY (NUM_MUN_SGAB)
REFERENCES L4_MUNICIPI_SGAB (NUM_MUN_SGAB);

CREATE OR REPLACE TABLE L4_EPIGRAF_IAE (
 
SECCIO VARCHAR(1) NOT NULL,
EPIGRAF_IAE VARCHAR(4) NOT NULL,
DESCR_IAE VARCHAR(50) NOT NULL,
TIP_TARIFA VARCHAR(1) NOT NULL,
TIP_QUOTA_TAMGREM VARCHAR(3) NOT NULL,
NIV_GEN_RES VARCHAR(1) NOT NULL,
COD_GEN_RES VARCHAR(1) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_EPIGRAF_IAE
PRIMARY KEY (SECCIO, EPIGRAF_IAE)
 
);

COMMENT ON TABLE L4_EPIGRAF_IAE IS
'Maestro de epígrafes IAE utilizado en el piloto. Ante la ausencia de datos reales se han definido categorías sintéticas basadas en las agrupaciones funcionales identificadas en los dossiers de Facturación.';

COMMENT ON COLUMN L4_EPIGRAF_IAE.SECCIO IS
'Categoría funcional de epígrafe utilizada exclusivamente en el piloto:
U=Doméstico,
C=Comercio,
I=Industria,
S=Servicios,
A=Administración Pública,
E=Entidades y Asociaciones,
P=Profesionales.';

CREATE OR REPLACE TABLE L4_CARRER (
 
NUM_MUN_SGAB VARCHAR(2) NOT NULL,
NUM_CARRER NUMBER(6,0) NOT NULL,
CLASSE_CARRER VARCHAR(4) NOT NULL,
NOM_ABREUJ_CARRER VARCHAR(18) NOT NULL,
TIP_DENOMIN_CARRER VARCHAR(1) NOT NULL,
NOM_COMPLET_CARRER VARCHAR(44) NOT NULL,
ID_CARRER_SAP VARCHAR(1) NOT NULL,
QL_CARRER VARCHAR(1) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_CARRER
PRIMARY KEY (NUM_MUN_SGAB, NUM_CARRER)
 
);

ALTER TABLE L4_CARRER
ADD CONSTRAINT FK_CARRER_MUNICIPI
FOREIGN KEY (NUM_MUN_SGAB)
REFERENCES L4_MUNICIPI_SGAB(NUM_MUN_SGAB);

CREATE OR REPLACE TABLE L4_FINCA (
 
NUM_MUN_SGAB VARCHAR(2) NOT NULL,
NUM_CARRER NUMBER(6,0) NOT NULL,
NUM_INI_FINCA VARCHAR(4) NOT NULL,
COMP_NUM_INI_FINCA VARCHAR(1) NOT NULL,
NUM_FIN_FINCA VARCHAR(4) NOT NULL,
COMP_NUM_FIN_FINCA VARCHAR(1) NOT NULL,
SIT_FINCA_ESPEC VARCHAR(1) NOT NULL,
ORD_FINCA_ESPEC VARCHAR(1) NOT NULL,
 
NUM_TORN_LECT_MENS NUMBER(4,0) NOT NULL,
ORD_FINCA_TORN_MEN NUMBER(3,0) NOT NULL,
NUM_DTE_POST_FINCA VARCHAR(2) NOT NULL,
ESTAT_FINCA VARCHAR(1) NOT NULL,
ID_GRUP_ELEV_FINCA VARCHAR(1) NOT NULL,
PRES_XARXA_FINCA NUMBER(3,0) NOT NULL,
CAT_FISCAL_FINCA VARCHAR(1) NOT NULL,
ALTURA_FINCA NUMBER(3,0) NOT NULL,
ID_FINCA_RENDA_LIM VARCHAR(1) NOT NULL,
NUM_EXP_RENDA_LIM VARCHAR(11) NOT NULL,
NUM_ZONA_RECOR VARCHAR(2) NOT NULL,
NUM_TRAVES NUMBER(7,0) NOT NULL,
CASA_RECOR_PERIOD VARCHAR(3) NOT NULL,
NUM_NUS_XARXA NUMBER(5,0) NOT NULL,
ID_LOT_LECT VARCHAR(3),
 
OBS_ADRE_INCOMPLET VARCHAR(24) NOT NULL,
PARTICULARIT_FINCA VARCHAR(25) NOT NULL,
LOCAL_CLAUS_FINCA VARCHAR(18) NOT NULL,
QL_COMPT_ELECTRON VARCHAR(1) NOT NULL,
NUM_DTE_MUNI_FINCA VARCHAR(2) NOT NULL,
QL_BATERIA_CABLE VARCHAR(2) NOT NULL,
CODI_UBICACIO_SAP VARCHAR(30),
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_FINCA PRIMARY KEY (
NUM_MUN_SGAB,
NUM_CARRER,
NUM_INI_FINCA,
COMP_NUM_INI_FINCA,
NUM_FIN_FINCA,
COMP_NUM_FIN_FINCA,
SIT_FINCA_ESPEC,
ORD_FINCA_ESPEC
)
 
);

ALTER TABLE L4_FINCA
ADD CONSTRAINT FK_FINCA_CARRER
FOREIGN KEY (NUM_MUN_SGAB, NUM_CARRER)
REFERENCES L4_CARRER(NUM_MUN_SGAB, NUM_CARRER);

CREATE OR REPLACE TABLE L4_RAMAL (
 
POLISSA_RAMAL VARCHAR(10) NOT NULL,
DVER_POLISSA_RAMAL VARCHAR(2) NOT NULL,
SIT_RAMAL VARCHAR(1) NOT NULL,
TIP_OPER_RAMAL VARCHAR(1) NOT NULL,
US_RAMAL VARCHAR(1) NOT NULL,
MATERIAL_RAMAL VARCHAR(1) NOT NULL,
DATA_INST_RAMAL DATE NOT NULL,
DIAMETRE_RAMAL NUMBER(3,0) NOT NULL,
SIT_CLAU_PAS VARCHAR(2) NOT NULL,
DATA_SIG_CTE_RAMAL DATE NOT NULL,
TIP_SUBM_CTE_RAMAL VARCHAR(1) NOT NULL,
NOMB_JOC_CLAUS_CTE NUMBER(3,0) NOT NULL,
DATA_PART_INST_RAM DATE NOT NULL,
NUM_PART_INST_RAM NUMBER(5,0) NOT NULL,
QL_ARQUETA_ARMARI VARCHAR(1) NOT NULL,
ESTAT_ARQUETA_ARM VARCHAR(1) NOT NULL,
ID_CIR_RECUP_AIGUA VARCHAR(1) NOT NULL,
NUM_SOL_LIC_AFEC VARCHAR(9),
DATA_SOL_BAIXA_RAM DATE NOT NULL,
DNI_NIF_CLIENT VARCHAR(9) NOT NULL,
NUM_MUN_SGAB VARCHAR(2) NOT NULL,
NUM_CARRER NUMBER(6,0) NOT NULL,
NUM_INI_FINCA VARCHAR(4) NOT NULL,
COMP_NUM_INI_FINCA VARCHAR(1) NOT NULL,
NUM_FIN_FINCA VARCHAR(4) NOT NULL,
COMP_NUM_FIN_FINCA VARCHAR(1) NOT NULL,
SIT_FINCA_ESPEC VARCHAR(1) NOT NULL,
ORD_FINCA_ESPEC VARCHAR(1) NOT NULL,
NUM_ORD_RAMAL NUMBER(2,0) NOT NULL,
POLISSA_RAMAL_AFEC VARCHAR(10),
DNI_NIF_CLIENT_ORI VARCHAR(9),
OBS_PRESA_RAMAL VARCHAR(16) NOT NULL,
RAMAL_CO NUMBER(7,0),
QL_TIPUS_DADES_C VARCHAR(2) NOT NULL,
QL_ANOT VARCHAR(1) NOT NULL,
SECCIO_CENSAL VARCHAR(10),
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_RAMAL
PRIMARY KEY (POLISSA_RAMAL)
 
);

ALTER TABLE L4_RAMAL
ADD CONSTRAINT FK_RAMAL_FINCA
FOREIGN KEY (
 
NUM_MUN_SGAB,
NUM_CARRER,
NUM_INI_FINCA,
COMP_NUM_INI_FINCA,
NUM_FIN_FINCA,
COMP_NUM_FIN_FINCA,
SIT_FINCA_ESPEC,
ORD_FINCA_ESPEC
 
)
REFERENCES L4_FINCA (
 
NUM_MUN_SGAB,
NUM_CARRER,
NUM_INI_FINCA,
COMP_NUM_INI_FINCA,
NUM_FIN_FINCA,
COMP_NUM_FIN_FINCA,
SIT_FINCA_ESPEC,
ORD_FINCA_ESPEC
 
);

CREATE OR REPLACE TABLE L4_SUBMIN_SERVEI (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
DVER_POLISSA_SUBM VARCHAR(2) NOT NULL,
 
TIP_SUBM_SERV VARCHAR(1) NOT NULL,
SIT_SUBM_SERV VARCHAR(1) NOT NULL,
 
DATA_CTE_SUBM_SERV DATE NOT NULL,
DATA_ALT_SUBM_SERV DATE NOT NULL,
DATA_RES_SUBM_SERV DATE NOT NULL,
 
IMP_FIANSA NUMBER(9,2) NOT NULL,
SIT_FIANSA VARCHAR(1) NOT NULL,
 
DATA_ULTIMA_FACT DATE NOT NULL,
 
QL_IDIOMA VARCHAR(1) NOT NULL,
 
ID_PAGA_IVA VARCHAR(1) NOT NULL,
 
US_AIGUA_SUBM VARCHAR(1) NOT NULL,
NOMB_HABIT_SUBM NUMBER(3,0) NOT NULL,
TIP_HABIT_SUBM VARCHAR(1) NOT NULL,
 
TIP_TAXA_TRR VARCHAR(1),
 
POLISSA_RAMAL VARCHAR(10) NOT NULL,
 
PIS_PORTA_DESTI VARCHAR(11) NOT NULL,
 
DNI_NIF_CLIENT VARCHAR(9) NOT NULL,
 
NUM_ENTITAT_COBRA VARCHAR(5) NOT NULL,
NUM_AGENCIA_APART VARCHAR(4) NOT NULL,
NUM_COMPTE_DEPEND VARCHAR(10) NOT NULL,
 
NOM_TITULAR_COMPTE VARCHAR(35) NOT NULL,
 
ID_QUOTA_SOCIAL VARCHAR(1),
ID_TARIFA_SOCIAL VARCHAR(1),
 
IND_SERVEI_SOCIAL VARCHAR(1),
IND_POB_ENERG VARCHAR(1),
 
NOM_COMERCIAL VARCHAR(50),
 
TIP_FACT_ENV VARCHAR(2),
 
CODI_PAIS VARCHAR(2),
 
NUM_COMPTE_IBAN VARCHAR(34),
 
IND_OKUPA VARCHAR(1),
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_SUBMIN_SERVEI
PRIMARY KEY (POLISSA_SUBM)
 
);

ALTER TABLE L4_SUBMIN_SERVEI
ADD CONSTRAINT FK_SUBMIN_RAMAL
FOREIGN KEY (POLISSA_RAMAL)
REFERENCES L4_RAMAL(POLISSA_RAMAL);


CREATE OR REPLACE TABLE L4_SUBMIN_IAE (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
SECCIO VARCHAR(1) NOT NULL,
EPIGRAF_IAE VARCHAR(4) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_SUBMIN_IAE
PRIMARY KEY (
POLISSA_SUBM,
SECCIO,
EPIGRAF_IAE
)
 
);

ALTER TABLE L4_SUBMIN_IAE
ADD CONSTRAINT FK_SUBMIN_IAE_SUBMIN_SERVEI
FOREIGN KEY (POLISSA_SUBM)
REFERENCES L4_SUBMIN_SERVEI(POLISSA_SUBM);
 
ALTER TABLE L4_SUBMIN_IAE
ADD CONSTRAINT FK_SUBMIN_IAE_EPIGRAF
FOREIGN KEY (SECCIO, EPIGRAF_IAE)
REFERENCES L4_EPIGRAF_IAE(SECCIO, EPIGRAF_IAE);

CREATE OR REPLACE TABLE L4_PADRO_TRR (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
TS_PADRO_TRR TIMESTAMP_NTZ NOT NULL,
TIP_TAXA_TRR VARCHAR(1) NOT NULL,
NOMB_HABIT_SUBM NUMBER(3,0) NOT NULL,
CONSUM_MES_BASE NUMBER(7,2) NOT NULL,
TIP_QUOTA_TRR VARCHAR(3) NOT NULL,
CONSUM_MIG_DIA NUMBER(9,4) NOT NULL,
NUMERO_EMPLEAT VARCHAR(8) NOT NULL,
SECCIO VARCHAR(1) NOT NULL,
EPIGRAF_IAE VARCHAR(4) NOT NULL,
PERC_BONIF_TRR NUMBER(5,2) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_PADRO_TRR
PRIMARY KEY (
POLISSA_SUBM,
TS_PADRO_TRR
)
 
);

ALTER TABLE L4_PADRO_TRR
ADD CONSTRAINT FK_PADRO_TRR_SUBMIN_SERVEI
FOREIGN KEY (POLISSA_SUBM)
REFERENCES L4_SUBMIN_SERVEI(POLISSA_SUBM);
 
ALTER TABLE L4_PADRO_TRR
ADD CONSTRAINT FK_PADRO_TRR_EPIGRAF
FOREIGN KEY (SECCIO, EPIGRAF_IAE)
REFERENCES L4_EPIGRAF_IAE(SECCIO, EPIGRAF_IAE);

CREATE OR REPLACE TABLE L4_PADRO_TAMGREM (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
TS_PADRO_TAMGREM TIMESTAMP_NTZ NOT NULL,
TIP_TAXA_TAMGREM VARCHAR(1) NOT NULL,
NOMB_HABIT_SUBM NUMBER(3,0) NOT NULL,
CONSUM_MES_BASE NUMBER(7,0) NOT NULL,
TIP_QUOTA_TAMGREM VARCHAR(3) NOT NULL,
CONSUM_MIG_DIA NUMBER(9,4) NOT NULL,
NUMERO_EMPLEAT VARCHAR(4) NOT NULL,
SECCIO VARCHAR(1) NOT NULL,
EPIGRAF_IAE VARCHAR(4) NOT NULL,
PERC_BONIF_TAMGREM NUMBER(5,2) NOT NULL,
IMP_CUOTA NUMBER(11,2) NOT NULL,
SUPERFICIE_REAL NUMBER(7,0) NOT NULL,
SUPERFICIE_POND NUMBER(9,2) NOT NULL,
NIV_GEN_RES VARCHAR(1) NOT NULL,
COD_GEN_RES VARCHAR(1) NOT NULL,
ORIGEN VARCHAR(2) NOT NULL,
ID_BONIF_DECGER VARCHAR(3) NOT NULL,
ID_LIMIT VARCHAR(2) NOT NULL,
SUBTIP_TAXA_TAMGREM VARCHAR(1) NOT NULL,
OBSERVACIONS VARCHAR(35) NOT NULL,
TS_ALTA TIMESTAMP_NTZ NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_PADRO_TAMGREM
PRIMARY KEY (
POLISSA_SUBM,
TS_PADRO_TAMGREM
)
 
);

ALTER TABLE L4_PADRO_TAMGREM
ADD CONSTRAINT FK_PADRO_TAMGREM_SUBMIN_SERVEI
FOREIGN KEY (POLISSA_SUBM)
REFERENCES L4_SUBMIN_SERVEI(POLISSA_SUBM);
 
ALTER TABLE L4_PADRO_TAMGREM
ADD CONSTRAINT FK_PADRO_TAMGREM_EPIGRAF
FOREIGN KEY (SECCIO, EPIGRAF_IAE)
REFERENCES L4_EPIGRAF_IAE(SECCIO, EPIGRAF_IAE);

CREATE OR REPLACE TABLE L4_HIST_SS_PE (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
TS_MOM_IND TIMESTAMP_NTZ NOT NULL,
TIP_COLECTIVO VARCHAR(2) NOT NULL,
DATA_INI_IND DATE NOT NULL,
DATA_FIN_IND DATE NOT NULL,
OBSERVACIONS VARCHAR(200) NOT NULL,
NUM_EMPLEAT VARCHAR(15) NOT NULL,
INFORME_SS VARCHAR(1) NOT NULL,
DATA_ENVIA_ACA DATE NOT NULL,
NOM_ACA_FITXER VARCHAR(35) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_HIST_SS_PE
PRIMARY KEY (
POLISSA_SUBM,
TIP_COLECTIVO,
TS_MOM_IND
)
 
);

ALTER TABLE L4_HIST_SS_PE
ADD CONSTRAINT FK_HIST_SS_PE_SUBMIN_SERVEI
FOREIGN KEY (POLISSA_SUBM)
REFERENCES L4_SUBMIN_SERVEI(POLISSA_SUBM);

CREATE OR REPLACE TABLE L4_SERVEI_EQ_CI (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
NOMB_BOQUES_25 NUMBER(3,0) NOT NULL,
NOMB_BOQUES_45 NUMBER(3,0) NOT NULL,
NOMB_BOQUES_70 NUMBER(3,0) NOT NULL,
NOMB_BOQUES_100 NUMBER(3,0) NOT NULL,
NOMB_SPRINCKLERS NUMBER(5,0) NOT NULL,
NUM_PRECINTE_BOCA NUMBER(3,0) NOT NULL,
ID_GRUP_ELEV_EQ_CI VARCHAR(1) NOT NULL,
ID_VALVULA_MOTOR VARCHAR(1) NOT NULL,
TIP_PETIC_RES VARCHAR(1) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_SERVEI_EQ_CI
PRIMARY KEY (POLISSA_SUBM)
 
);

ALTER TABLE L4_SERVEI_EQ_CI
ADD CONSTRAINT FK_SERVEI_EQ_CI_SUBMIN_SERVEI
FOREIGN KEY (POLISSA_SUBM)
REFERENCES L4_SUBMIN_SERVEI(POLISSA_SUBM);

CREATE OR REPLACE TABLE L4_SERVEI_FACTURAR (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
DATA_FIN_FACT DATE NOT NULL,
CALCUL_CONSUM_SERV VARCHAR(2) NOT NULL,
DIES_CONSUM_SERV NUMBER(5,0) NOT NULL,
NOMB_BOQ_25_SERV NUMBER(3,0) NOT NULL,
NOMB_BOQ_45_SERV NUMBER(3,0) NOT NULL,
NOMB_BOQ_70_SERV NUMBER(3,0) NOT NULL,
NOMB_BOQ_100_SERV NUMBER(3,0) NOT NULL,
NOMB_SPRINCK_SERV NUMBER(5,0) NOT NULL,
ID_BUTLLETA VARCHAR(1) NOT NULL,
ID_LOT_LECT VARCHAR(3) NOT NULL,
ANY_CALENDARI VARCHAR(2) NOT NULL,
MES_CALENDARI VARCHAR(2) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_SERVEI_FACTURAR
PRIMARY KEY (
POLISSA_SUBM,
DATA_FIN_FACT
)
 
);

ALTER TABLE L4_SERVEI_FACTURAR
ADD CONSTRAINT FK_SERVEI_FACTURAR_SUBMIN_SERVEI
FOREIGN KEY (POLISSA_SUBM)
REFERENCES L4_SUBMIN_SERVEI(POLISSA_SUBM);

CREATE OR REPLACE TABLE L4_CONVENI_FRAU (
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
NUM_MUN_CONV_FRAU VARCHAR(2) NOT NULL,
ADRE_CONV_FRAU VARCHAR(35) NOT NULL,
COD_POST_CONV_FRAU VARCHAR(5) NOT NULL,
DEL_CREACIO_CONV_F VARCHAR(2) NOT NULL,
DATA_CREA_C_FRA DATE NOT NULL,
POLISSA_RAMAL VARCHAR(10) NOT NULL,
 
ID_CARGA NUMBER,
FECHA_EXTRACCION TIMESTAMP_NTZ,
FECHA_CARGA TIMESTAMP_NTZ,
SISTEMA_ORIGEN VARCHAR(30),
TABLA_ORIGEN VARCHAR(50),
 
CONSTRAINT PK_CONVENI_FRAU
PRIMARY KEY (POLISSA_SUBM)
 
);

ALTER TABLE L4_CONVENI_FRAU
ADD CONSTRAINT FK_CONVENI_FRAU_RAMAL
FOREIGN KEY (POLISSA_RAMAL)
REFERENCES L4_RAMAL(POLISSA_RAMAL);

ALTER TABLE L4_CONVENI_FRAU
ADD CONSTRAINT FK_CONVENI_FRAU_MUNICIPI
FOREIGN KEY (NUM_MUN_CONV_FRAU)
REFERENCES L4_MUNICIPI_SGAB(NUM_MUN_SGAB);

ALTER TABLE L4_CONVENI_FRAU
ADD CONSTRAINT FK_CONVENI_FRAU_SUBMIN_SERVEI
FOREIGN KEY (POLISSA_SUBM)
REFERENCES L4_SUBMIN_SERVEI (POLISSA_SUBM);

CREATE OR REPLACE TABLE L4_FACT_RESUM (
 
ID_EMPRESA VARCHAR(2) NOT NULL,
ANY_FACTURA VARCHAR(4) NOT NULL,
NUM_FACTURA NUMBER(7,0) NOT NULL,
 
QL_EMPLEAT_SGAB VARCHAR(1) NOT NULL,
FREQ_FACT VARCHAR(1) NOT NULL,
 
M3_BLOC1 NUMBER(7,0) NOT NULL,
M3_BLOC2 NUMBER(7,0) NOT NULL,
M3_BLOC3 NUMBER(7,0) NOT NULL,
M3_BLOC4 NUMBER(7,0) DEFAULT 0 NOT NULL,
M3_BLOC5 NUMBER(7,0) DEFAULT 0 NOT NULL,
 
IMP_TOTAL_FACT NUMBER(11,2) NOT NULL,
IMP_AIGUA_IVA NUMBER(11,2) NOT NULL,
 
ID_RECUPERACIO VARCHAR(1) NOT NULL,
ID_REGULARITZACIO VARCHAR(1) NOT NULL,
 
DATA_CARREC_RECAP DATE NOT NULL,
 
IDEN_LOT_LECT_FACT VARCHAR(3) NOT NULL,
NUM_PARTICIO NUMBER(2,0) NOT NULL,
 
POLISSA_SUBM VARCHAR(10) NOT NULL,
 
DATA_FIN_FACT DATE NOT NULL,
 
ID_LOT_FACT VARCHAR(3) NOT NULL,
ANY_CALENDARI VARCHAR(2) NOT NULL,
MES_CALENDARI VARCHAR(2) NOT NULL,
 
ID_CONCEPTES VARCHAR(1) NOT NULL,
ID_DECLARADA VARCHAR(1) NOT NULL,
 
DNI_NIF_CLIENT VARCHAR(9) NOT NULL,
 
QL_GESTIO_FACT VARCHAR(1) NOT NULL,
QL_TIP_COBRA VARCHAR(1) NOT NULL,
 
NUM_ENTITAT_COBR VARCHAR(5) NOT NULL,
NUM_AGENCIA_APAR VARCHAR(4) NOT NULL,
NUM_COMPTE_DEPEN VARCHAR(10) NOT NULL,
DVER_COMPTE_BANC VARCHAR(2) NOT NULL,
 
TIP_FACTURA VARCHAR(2) NOT NULL,
 
DATA_EMISS_FACT DATE NOT NULL,
DATA_INI_FACT DATE NOT NULL,
 
QL_RESUM_COMPTABLE VARCHAR(1) NOT NULL,
TIP_QTA_SERV_FACT NUMBER(3,0) NOT NULL,
 
ID_CALCUL_DIARI VARCHAR(1) NOT NULL,
US_AIGUA_SUBM_FACT VARCHAR(1) NOT NULL,
TIP_HABIT_SUBM_FA VARCHAR(1) NOT NULL,
 
NOMB_HABIT_FACT NUMBER(3,0) NOT NULL,
 
SIT_SUBM_SERV_FACT VARCHAR(1) NOT NULL,
QL_IDIOMA_FACT VARCHAR(1) NOT NULL,
 
PUBLI_OFI_TARI_FA VARCHAR(8) NOT NULL,
ID_CARREC_SOCIETAT VARCHAR(1) NOT NULL,
QL_MONEDA VARCHAR(1) NOT NULL,
 
TIP_SUBM_SERV VARCHAR(1) NOT NULL,
 
NOM_CLIENT VARCHAR(35) NOT NULL,
 
NUM_INDEX VARCHAR(10),
APROVADA_FACT VARCHAR(10),
 
QL_TIP_COBRA_INI VARCHAR(1) DEFAULT ' ' NOT NULL,
QL_ENVIO_FACT VARCHAR(1) DEFAULT ' ' NOT NULL,
TIP_DOMESTIC VARCHAR(1) DEFAULT ' ' NOT NULL,
QL_DCL_CAI VARCHAR(1) DEFAULT ' ' NOT NULL,
 
TIP_FACT_ENV VARCHAR(2) DEFAULT 'FP' NOT NULL,
 
EMISSORA VARCHAR(3) DEFAULT ' ' NOT NULL,
NUM_COMPTE_IBAN VARCHAR(34) DEFAULT ' ' NOT NULL,
 
TIP_FACT_SII VARCHAR(1) DEFAULT ' ' NOT NULL,
TIPUS_FACTURA VARCHAR(1) DEFAULT ' ' NOT NULL,
 
CONSTRAINT PK_FACT_RESUM
PRIMARY KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
);

ALTER TABLE L4_FACT_RESUM
CLUSTER BY (
POLISSA_SUBM,
DATA_FIN_FACT
);

ALTER TABLE L4_FACT_RESUM
ADD SEARCH OPTIMIZATION
ON EQUALITY (
POLISSA_SUBM,
DNI_NIF_CLIENT,
NUM_FACTURA
);

ALTER TABLE L4_FACT_RESUM
ADD CONSTRAINT FK_FACT_RESUM_SUBMIN_SERVEI
FOREIGN KEY (
POLISSA_SUBM
)
REFERENCES L4_SUBMIN_SERVEI (
POLISSA_SUBM
);

CREATE OR REPLACE TABLE L4_FACT_AIGUA (
 
NUM_PARTICIO NUMBER(2,0) NOT NULL,
ID_EMPRESA VARCHAR(2) NOT NULL,
ANY_FACTURA VARCHAR(4) NOT NULL,
NUM_FACTURA NUMBER(7,0) NOT NULL,
 
DIAM_COMP_FACT NUMBER(3,0) NOT NULL,
DIAM_COMP_SEC_FACT NUMBER(3,0) NOT NULL,
MARCA_COMP_FACT VARCHAR(3) NOT NULL,
NUM_COMP_FACT VARCHAR(9) NOT NULL,
 
PROPIETAT_COMP_FA VARCHAR(1) NOT NULL,
 
CABAL_NOMINAL_CTE NUMBER(3,1) NOT NULL,
 
IMP_QTA_SERV NUMBER(11,2) NOT NULL,
 
PREU_M3_BLOC1_FACT NUMBER(9,4) NOT NULL,
IMP_BLOC1 NUMBER(11,2) NOT NULL,
 
PREU_M3_BLOC2_FACT NUMBER(9,4) NOT NULL,
IMP_BLOC2 NUMBER(11,2) NOT NULL,
 
PREU_M3_BLOC3_FACT NUMBER(9,4) NOT NULL,
IMP_BLOC3 NUMBER(11,2) NOT NULL,
 
TIP_CT_XBASICA_FAC VARCHAR(1) NOT NULL,
BASE_CT_XBASICA NUMBER(7,0) NOT NULL,
PREU_CT_XBASICA_FA NUMBER(9,4) NOT NULL,
IMP_CT_XBASICA NUMBER(11,2) NOT NULL,
 
TIP_TCG_SUBM_FACT VARCHAR(1) NOT NULL,
BASE_TCG_SUBM NUMBER(7,0) NOT NULL,
PREU_TCG_SUBM_FACT NUMBER(9,4) NOT NULL,
IMP_TCG_SUBM NUMBER(11,2) NOT NULL,
 
TIP_CLAVAG_FACT VARCHAR(1) NOT NULL,
BASE_CLAVAG NUMBER(11,2) NOT NULL,
PREU_CLAVAG_FACT NUMBER(9,4) NOT NULL,
IMP_CLAVAG NUMBER(11,2) NOT NULL,
 
TIP_SANEJA_FACT VARCHAR(1) NOT NULL,
BASE_SANEJA NUMBER(7,0) NOT NULL,
PREU_SANEJA_FACT NUMBER(9,4) NOT NULL,
IMP_SANEJA NUMBER(11,2) NOT NULL,
 
BASE_IVA_SANEJA NUMBER(11,2) NOT NULL,
IMP_IVA_SANEJA NUMBER(11,2) NOT NULL,
 
BASE_IVA NUMBER(11,2) NOT NULL,
PERCENT_IVA_FACT NUMBER(5,2) NOT NULL,
IMP_IVA NUMBER(11,2) NOT NULL,
 
TIP_ERSU_FACT VARCHAR(1) NOT NULL,
BASE_ERSU NUMBER(7,0) NOT NULL,
PREU_ERSU_FACT NUMBER(9,4) NOT NULL,
IMP_ERSU NUMBER(11,2) NOT NULL,
 
TIP_CIH_FACT VARCHAR(1) NOT NULL,
 
BASE_CIH_BLOC1 NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC1_FA NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC1 NUMBER(11,2) NOT NULL,
 
BASE_CIH_BLOC2 NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC2_FA NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC2 NUMBER(11,2) NOT NULL,
 
BASE_CIH_BLOC3 NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC3_FA NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC3 NUMBER(11,2) NOT NULL,
 
CABAL_CTE NUMBER(5,1) DEFAULT 0 NOT NULL,
COEF_CIH_IND_FAC NUMBER(5,3) DEFAULT 0 NOT NULL,
QL_1999_2000 VARCHAR(1) DEFAULT ' ' NOT NULL,
 
NOMBRE_PERSONES NUMBER(3,0) DEFAULT 0 NOT NULL,
 
LIMIT_TRAM1_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
LIMIT_TRAM2_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
 
LIMIT_CAI1_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
LIMIT_CLAV1_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
LIMIT_CAI2_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
 
NOMBRE_PER_CAI NUMBER(3,0) DEFAULT 0 NOT NULL,
NOMBRE_PER_TMTR NUMBER(3,0) DEFAULT 0 NOT NULL,
 
NUM_COMPT_T_FACT VARCHAR(12) DEFAULT ' ' NOT NULL,
 
PREU_M3_BLOC4_FACT NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_BLOC4 NUMBER(11,2) DEFAULT 0 NOT NULL,
 
PREU_M3_BLOC5_FACT NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_BLOC5 NUMBER(11,2) DEFAULT 0 NOT NULL,
 
LIMIT_TRAM3_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
LIMIT_TRAM4_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
LIMIT_CAI3_FACT NUMBER(7,0) DEFAULT 0 NOT NULL,
 
CONSTRAINT PK_FACT_AIGUA
PRIMARY KEY (
NUM_PARTICIO,
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
);

ALTER TABLE L4_FACT_AIGUA
CLUSTER BY (
ANY_FACTURA,
NUM_FACTURA
);

ALTER TABLE L4_FACT_AIGUA
ADD CONSTRAINT FK_FACT_AIGUA_FACT_RESUM
FOREIGN KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
REFERENCES L4_FACT_RESUM (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
);

CREATE OR REPLACE TABLE L4_FACT_CONCEPTE (
 
NUM_PARTICIO NUMBER(2,0) NOT NULL,
ID_EMPRESA VARCHAR(2) NOT NULL,
ANY_FACTURA VARCHAR(4) NOT NULL,
NUM_FACTURA NUMBER(7,0) NOT NULL,
 
NUM_LINEA NUMBER(3,0) NOT NULL,
NUM_CONCEPTE VARCHAR(3) NOT NULL,
 
BASE_CONCEPTE NUMBER(11,2) NOT NULL,
TIP_TAXA_CONCEP VARCHAR(1) NOT NULL,
PREU_CONCEPTE NUMBER(11,4) NOT NULL,
IMP_CONCEPTE NUMBER(11,2) NOT NULL,
IVA_APLICAT_CONC NUMBER(5,2) NOT NULL,
 
OBSER_CONCEPTE VARCHAR(80) NOT NULL,
 
CONSTRAINT PK_FACT_CONCEPTE
PRIMARY KEY (
NUM_PARTICIO,
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA,
NUM_LINEA,
NUM_CONCEPTE
)
);

ALTER TABLE L4_FACT_CONCEPTE
CLUSTER BY (
ANY_FACTURA,
NUM_FACTURA
);

ALTER TABLE L4_FACT_CONCEPTE
ADD SEARCH OPTIMIZATION
ON EQUALITY (
NUM_CONCEPTE
);

ALTER TABLE L4_FACT_CONCEPTE
ADD CONSTRAINT FK_FACT_CONCEPTE_FACT_RESUM
FOREIGN KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
REFERENCES L4_FACT_RESUM (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
);

CREATE OR REPLACE TABLE L4_FACT_REGUL (
 
ID_EMPRESA VARCHAR(2) NOT NULL,
ANY_FACTURA VARCHAR(4) NOT NULL,
NUM_FACTURA NUMBER(7,0) NOT NULL,
 
DATA_FIN_PER_INCID DATE NOT NULL,
 
M3_BLOC1_RG NUMBER(7,0) NOT NULL,
PREU_M3_BLOC1_RG NUMBER(9,4) NOT NULL,
IMP_BLOC1_RG NUMBER(11,2) NOT NULL,
 
M3_BLOC2_RG NUMBER(7,0) NOT NULL,
PREU_M3_BLOC2_RG NUMBER(9,4) NOT NULL,
IMP_BLOC2_RG NUMBER(11,2) NOT NULL,
 
M3_BLOC3_RG NUMBER(7,0) NOT NULL,
PREU_M3_BLOC3_RG NUMBER(9,4) NOT NULL,
IMP_BLOC3_RG NUMBER(11,2) NOT NULL,
 
TIP_CT_XBASICA_RG VARCHAR(1) NOT NULL,
BASE_CT_XBASICA_RG NUMBER(7,0) NOT NULL,
PREU_CT_XBASICA_RG NUMBER(9,4) NOT NULL,
IMP_CT_XBASICA_RG NUMBER(11,2) NOT NULL,
 
TIP_TCG_SUBM_RG VARCHAR(1) NOT NULL,
BASE_TCG_SUBM_RG NUMBER(7,0) NOT NULL,
PREU_TCG_SUBM_RG NUMBER(9,4) NOT NULL,
IMP_TCG_SUBM_RG NUMBER(11,2) NOT NULL,
 
BASE_CTG_SUBM_RG NUMBER(11,2) NOT NULL,
PERCEN_CTG_SUBM_RG NUMBER(5,2) NOT NULL,
IMP_CTG_SUBM_RG NUMBER(11,2) NOT NULL,
 
IMP_CAN_BAELLS_RG NUMBER(11,2) NOT NULL,
IMP_CAN_TER_RG NUMBER(11,2) NOT NULL,
IMP_PRODUC_BRUT_RG NUMBER(11,2) NOT NULL,
 
TIP_CLAVAG_RG VARCHAR(1) NOT NULL,
BASE_CLAVAG_RG NUMBER(11,2) NOT NULL,
PREU_CLAVAG_RG NUMBER(9,4) NOT NULL,
IMP_CLAVAG_RG NUMBER(11,2) NOT NULL,
 
TIP_SANEJA_RG VARCHAR(1) NOT NULL,
BASE_SANEJA_RG NUMBER(7,0) NOT NULL,
PREU_SANEJA_RG NUMBER(9,4) NOT NULL,
IMP_SANEJA_RG NUMBER(11,2) NOT NULL,
 
TIP_ERSU_RG VARCHAR(1) NOT NULL,
BASE_ERSU_RG NUMBER(7,0) NOT NULL,
PREU_ERSU_RG NUMBER(9,4) NOT NULL,
IMP_ERSU_RG NUMBER(11,2) NOT NULL,
 
TIP_CIH_RG VARCHAR(1) NOT NULL,
 
BASE_CIH_BLOC1_RG NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC1_RG NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC1_RG NUMBER(11,2) NOT NULL,
 
BASE_CIH_BLOC2_RG NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC2_RG NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC2_RG NUMBER(11,2) NOT NULL,
 
BASE_CIH_BLOC3_RG NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC3_RG NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC3_RG NUMBER(11,2) NOT NULL,
 
TIP_CAI_RG VARCHAR(1) DEFAULT ' ' NOT NULL,
 
BASE_CAI_T1_RG NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CAI_T1_RG NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CAI_T1_RG NUMBER(11,2) DEFAULT 0 NOT NULL,
 
BASE_CAI_T2_RG NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CAI_T2_RG NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CAI_T2_RG NUMBER(11,2) DEFAULT 0 NOT NULL,
 
COEF_CAI_RG NUMBER(5,3) DEFAULT 0 NOT NULL,
 
BASE_CLA_T2_RG NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CLA_T2_RG NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CLA_T2_RG NUMBER(11,2) DEFAULT 0 NOT NULL,
 
BASE_CAI_T3_RG NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CAI_T3_RG NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CAI_T3_RG NUMBER(11,2) DEFAULT 0 NOT NULL,
 
BASE_CAI_T4_RG NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CAI_T4_RG NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CAI_T4_RG NUMBER(11,2) DEFAULT 0 NOT NULL,
 
M3_BLOC4_RG NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_M3_BLOC4_RG NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_BLOC4_RG NUMBER(11,2) DEFAULT 0 NOT NULL,
 
M3_BLOC5_RG NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_M3_BLOC5_RG NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_BLOC5_RG NUMBER(11,2) DEFAULT 0 NOT NULL,
 
CONSTRAINT PK_FACT_REGUL
PRIMARY KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA,
DATA_FIN_PER_INCID
)
);

/*
ALTER TABLE L4_FACT_REGUL
CLUSTER BY (
ANY_FACTURA,
NUM_FACTURA
);
*/

ALTER TABLE L4_FACT_REGUL
ADD CONSTRAINT FK_FACT_REGUL_FACT_RESUM
FOREIGN KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
REFERENCES L4_FACT_RESUM (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
);


CREATE OR REPLACE TABLE L4_FACT_RECUP (
 
ID_EMPRESA VARCHAR(2) NOT NULL,
ANY_FACTURA VARCHAR(4) NOT NULL,
NUM_FACTURA NUMBER(7,0) NOT NULL,
 
IMP_QTA_SERV_RC NUMBER(11,2) NOT NULL,
 
M3_BLOC1_RC NUMBER(7,0) NOT NULL,
PREU_M3_BLOC1_RC NUMBER(9,4) NOT NULL,
IMP_BLOC1_RC NUMBER(11,2) NOT NULL,
 
M3_BLOC2_RC NUMBER(7,0) NOT NULL,
PREU_M3_BLOC2_RC NUMBER(9,4) NOT NULL,
IMP_BLOC2_RC NUMBER(11,2) NOT NULL,
 
M3_BLOC3_RC NUMBER(7,0) NOT NULL,
PREU_M3_BLOC3_RC NUMBER(9,4) NOT NULL,
IMP_BLOC3_RC NUMBER(11,2) NOT NULL,
 
BASE_CT_XBASICA_RC NUMBER(7,0) NOT NULL,
PREU_CT_XBASICA_RC NUMBER(9,4) NOT NULL,
IMP_CT_XBASICA_RC NUMBER(11,2) NOT NULL,
 
BASE_TCG_SUBM_RC NUMBER(7,0) NOT NULL,
PREU_TCG_SUBM_RC NUMBER(9,4) NOT NULL,
IMP_TCG_SUBM_RC NUMBER(11,2) NOT NULL,
 
BASE_CLAVAG_RC NUMBER(11,2) NOT NULL,
PREU_CLAVAG_RC NUMBER(9,4) NOT NULL,
IMP_CLAVAG_RC NUMBER(11,2) NOT NULL,
 
BASE_SANEJA_RC NUMBER(7,0) NOT NULL,
PREU_SANEJA_RC NUMBER(9,4) NOT NULL,
IMP_SANEJA_RC NUMBER(11,2) NOT NULL,
 
BASE_ERSU_RC NUMBER(7,0) NOT NULL,
PREU_ERSU_RC NUMBER(9,4) NOT NULL,
IMP_ERSU_RC NUMBER(11,2) NOT NULL,
 
BASE_CIH_BLOC1_RC NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC1_RC NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC1_RC NUMBER(11,2) NOT NULL,
 
BASE_CIH_BLOC2_RC NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC2_RC NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC2_RC NUMBER(11,2) NOT NULL,
 
BASE_CIH_BLOC3_RC NUMBER(7,0) NOT NULL,
PREU_CIH_BLOC3_RC NUMBER(9,4) NOT NULL,
IMP_CIH_BLOC3_RC NUMBER(11,2) NOT NULL,
 
IMP_BONIF_QTA_RC NUMBER(9,2) NOT NULL,
 
BASE_CAI_T1_RC NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CAI_T1_RC NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CAI_T1_RC NUMBER(11,2) DEFAULT 0 NOT NULL,
 
BASE_CAI_T2_RC NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CAI_T2_RC NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CAI_T2_RC NUMBER(11,2) DEFAULT 0 NOT NULL,
 
BASE_CLA_T2_RC NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CLA_T2_RC NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CLA_T2_RC NUMBER(11,2) DEFAULT 0 NOT NULL,
 
BASE_CAI_T3_RC NUMBER(7,0) DEFAULT 0 NOT NULL,
PREU_CAI_T3_RC NUMBER(9,4) DEFAULT 0 NOT NULL,
IMP_CAI_T3_RC NUMBER(11,2) DEFAULT 0 NOT NULL,
 
CONSTRAINT PK_FACT_RECUP
PRIMARY KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
);

/*
ALTER TABLE L4_FACT_RECUP
CLUSTER BY (
ANY_FACTURA,
NUM_FACTURA
);
*/

ALTER TABLE L4_FACT_RECUP
ADD CONSTRAINT FK_FACT_RECUP_FACT_RESUM
FOREIGN KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
REFERENCES L4_FACT_RESUM (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
);

CREATE OR REPLACE TABLE L4_SITUACIO_FACT (
 
NUM_PARTICIO NUMBER(2,0) NOT NULL,
 
ID_EMPRESA VARCHAR(2) NOT NULL,
ANY_FACTURA VARCHAR(4) NOT NULL,
NUM_FACTURA NUMBER(7,0) NOT NULL,
 
MOM_SIT_FACT TIMESTAMP_NTZ NOT NULL,
 
TIP_SIT_FACT VARCHAR(2) NOT NULL,
CAUSA_SIT_FACT VARCHAR(2) NOT NULL,
 
CONSTRAINT PK_SITUACIO_FACT
PRIMARY KEY (
NUM_PARTICIO,
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA,
MOM_SIT_FACT
)
);

ALTER TABLE L4_SITUACIO_FACT
CLUSTER BY (
MOM_SIT_FACT
);

ALTER TABLE L4_SITUACIO_FACT
ADD SEARCH OPTIMIZATION
ON EQUALITY (
TIP_SIT_FACT,
CAUSA_SIT_FACT
);

ALTER TABLE L4_SITUACIO_FACT
ADD CONSTRAINT FK_SITUACIO_FACT_FACT_RESUM
FOREIGN KEY (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
)
REFERENCES L4_FACT_RESUM (
ID_EMPRESA,
ANY_FACTURA,
NUM_FACTURA
);

/* Despues de cargar datos, ejecutar
	SYSTEM$CLUSTERING_INFORMATION('L4_FACT_RESUM');
	
*/

